[package]
name = "tapu-simu"
version = "0.2.0"
edition = "2021"
description = "High-performance Pokemon battle simulator - Rust port of Pokemon Showdown"
license = "MIT"
repository = "https://github.com/mingu600/tapu-simu"

[lib]
name = "tapu_simu"
path = "src/lib.rs"

[[bin]]
name = "tapu-simu"
path = "src/main.rs"

[[bin]]
name = "test-data-loading"
path = "src/bin/test_data_loading.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
chacha20 = "0.9"
thiserror = "1.0"
anyhow = "1.0"
indexmap = "2.0"
smallvec = { version = "1.11", features = ["serde"] }
ahash = "0.8"
regex = "1.0"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
proptest = "1.0"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[profile.bench]
debug = true