use serde::{Deserialize, Serialize};
use crate::types::from_string::FromNormalizedString;
use std::fmt;

/// Abilities enum with complete Pokemon Showdown data coverage
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Abilities {
    ADAPTABILITY,
    AERILATE,
    AFTERMATH,
    AIRLOCK,
    ANALYTIC,
    ANGERPOINT,
    ANGERSHELL,
    ANTICIPATION,
    ARENATRAP,
    ARMORTAIL,
    AROMAVEIL,
    ASONEGLASTRIER,
    ASONESPECTRIER,
    AURABREAK,
    BADDREAMS,
    BALLFETCH,
    BATTERY,
    BATTLEARMOR,
    BATTLEBOND,
    BEADSOFRUIN,
    BEASTBOOST,
    BERSERK,
    BIGPECKS,
    BLAZE,
    BULLETPROOF,
    CHEEKPOUCH,
    CHILLINGNEIGH,
    CHLOROPHYLL,
    CLEARBODY,
    CLOUDNINE,
    COLORCHANGE,
    COMATOSE,
    COMMANDER,
    COMPETITIVE,
    COMPOUNDEYES,
    CONTRARY,
    CORROSION,
    COSTAR,
    COTTONDOWN,
    CUDCHEW,
    CURIOUSMEDICINE,
    CURSEDBODY,
    CUTECHARM,
    DAMP,
    DANCER,
    DARKAURA,
    DAUNTLESSSHIELD,
    DAZZLING,
    DEFEATIST,
    DEFIANT,
    DELTASTREAM,
    DESOLATELAND,
    DISGUISE,
    DOWNLOAD,
    DRAGONSMAW,
    DRIZZLE,
    DROUGHT,
    DRYSKIN,
    EARLYBIRD,
    EARTHEATER,
    EFFECTSPORE,
    ELECTRICSURGE,
    ELECTROMORPHOSIS,
    EMBODYASPECTCORNERSTONE,
    EMBODYASPECTHEARTHFLAME,
    EMBODYASPECTTEAL,
    EMBODYASPECTWELLSPRING,
    EMERGENCYEXIT,
    FAIRYAURA,
    FILTER,
    FLAMEBODY,
    FLAREBOOST,
    FLASHFIRE,
    FLOWERGIFT,
    FLOWERVEIL,
    FLUFFY,
    FORECAST,
    FOREWARN,
    FRIENDGUARD,
    FRISK,
    FULLMETALBODY,
    FURCOAT,
    GALEWINGS,
    GALVANIZE,
    GLUTTONY,
    GOODASGOLD,
    GOOEY,
    GORILLATACTICS,
    GRASSPELT,
    GRASSYSURGE,
    GRIMNEIGH,
    GUARDDOG,
    GULPMISSILE,
    GUTS,
    HADRONENGINE,
    HARVEST,
    HEALER,
    HEATPROOF,
    HEAVYMETAL,
    HONEYGATHER,
    HOSPITALITY,
    HUGEPOWER,
    HUNGERSWITCH,
    HUSTLE,
    HYDRATION,
    HYPERCUTTER,
    ICEBODY,
    ICEFACE,
    ICESCALES,
    ILLUMINATE,
    ILLUSION,
    IMMUNITY,
    IMPOSTER,
    INFILTRATOR,
    INNARDSOUT,
    INNERFOCUS,
    INSOMNIA,
    INTIMIDATE,
    INTREPIDSWORD,
    IRONBARBS,
    IRONFIST,
    JUSTIFIED,
    KEENEYE,
    KLUTZ,
    LEAFGUARD,
    LEVITATE,
    LIBERO,
    LIGHTMETAL,
    LIGHTNINGROD,
    LIMBER,
    LINGERINGAROMA,
    LIQUIDOOZE,
    LIQUIDVOICE,
    LONGREACH,
    MAGICBOUNCE,
    MAGICGUARD,
    MAGICIAN,
    MAGMAARMOR,
    MAGNETPULL,
    MARVELSCALE,
    MEGALAUNCHER,
    MERCILESS,
    MIMICRY,
    MINDSEYE,
    MINUS,
    MIRRORARMOR,
    MISTYSURGE,
    MOLDBREAKER,
    MOODY,
    MOTORDRIVE,
    MOUNTAINEER,
    MOXIE,
    MULTISCALE,
    MULTITYPE,
    MUMMY,
    MYCELIUMMIGHT,
    NATURALCURE,
    NEUROFORCE,
    NEUTRALIZINGGAS,
    NOABILITY,
    NOGUARD,
    NONE,
    NORMALIZE,
    OBLIVIOUS,
    OPPORTUNIST,
    ORICHALCUMPULSE,
    OVERCOAT,
    OVERGROW,
    OWNTEMPO,
    PARENTALBOND,
    PASTELVEIL,
    PERISHBODY,
    PERSISTENT,
    PICKPOCKET,
    PICKUP,
    PIXILATE,
    PLUS,
    POISONHEAL,
    POISONPOINT,
    POISONPUPPETEER,
    POISONTOUCH,
    POWERCONSTRUCT,
    POWEROFALCHEMY,
    POWERSPOT,
    PRANKSTER,
    PRESSURE,
    PRIMORDIALSEA,
    PRISMARMOR,
    PROPELLERTAIL,
    PROTEAN,
    PROTOSYNTHESIS,
    PSYCHICSURGE,
    PUNKROCK,
    PUREPOWER,
    PURIFYINGSALT,
    QUARKDRIVE,
    QUEENLYMAJESTY,
    QUICKDRAW,
    QUICKFEET,
    RAINDISH,
    RATTLED,
    REBOUND,
    RECEIVER,
    RECKLESS,
    REFRIGERATE,
    REGENERATOR,
    RIPEN,
    RIVALRY,
    RKSSYSTEM,
    ROCKHEAD,
    ROCKYPAYLOAD,
    ROUGHSKIN,
    RUNAWAY,
    SANDFORCE,
    SANDRUSH,
    SANDSPIT,
    SANDSTREAM,
    SANDVEIL,
    SAPSIPPER,
    SCHOOLING,
    SCRAPPY,
    SCREENCLEANER,
    SEEDSOWER,
    SERENEGRACE,
    SHADOWSHIELD,
    SHADOWTAG,
    SHARPNESS,
    SHEDSKIN,
    SHEERFORCE,
    SHELLARMOR,
    SHIELDDUST,
    SHIELDSDOWN,
    SIMPLE,
    SKILLLINK,
    SLOWSTART,
    SLUSHRUSH,
    SNIPER,
    SNOWCLOAK,
    SNOWWARNING,
    SOLARPOWER,
    SOLIDROCK,
    SOULHEART,
    SOUNDPROOF,
    SPEEDBOOST,
    STAKEOUT,
    STALL,
    STALWART,
    STAMINA,
    STANCECHANGE,
    STATIC,
    STEADFAST,
    STEAMENGINE,
    STEELWORKER,
    STEELYSPIRIT,
    STENCH,
    STICKYHOLD,
    STORMDRAIN,
    STRONGJAW,
    STURDY,
    SUCTIONCUPS,
    SUPERLUCK,
    SUPERSWEETSYRUP,
    SUPREMEOVERLORD,
    SURGESURFER,
    SWARM,
    SWEETVEIL,
    SWIFTSWIM,
    SWORDOFRUIN,
    SYMBIOSIS,
    SYNCHRONIZE,
    TABLETSOFRUIN,
    TANGLEDFEET,
    TANGLINGHAIR,
    TECHNICIAN,
    TELEPATHY,
    TERAFORMZERO,
    TERASHELL,
    TERASHIFT,
    TERAVOLT,
    THERMALEXCHANGE,
    THICKFAT,
    TINTEDLENS,
    TORRENT,
    TOUGHCLAWS,
    TOXICBOOST,
    TOXICCHAIN,
    TOXICDEBRIS,
    TRACE,
    TRANSISTOR,
    TRIAGE,
    TRUANT,
    TURBOBLAZE,
    UNAWARE,
    UNBURDEN,
    UNNERVE,
    UNSEENFIST,
    VESSELOFRUIN,
    VICTORYSTAR,
    VITALSPIRIT,
    VOLTABSORB,
    WANDERINGSPIRIT,
    WATERABSORB,
    WATERBUBBLE,
    WATERCOMPACTION,
    WATERVEIL,
    WEAKARMOR,
    WELLBAKEDBODY,
    WHITESMOKE,
    WIMPOUT,
    WINDPOWER,
    WINDRIDER,
    WONDERGUARD,
    WONDERSKIN,
    ZENMODE,
    ZEROTOHERO,
}

impl Abilities {
    /// Get the normalized string representation of this abilities
    pub fn as_str(&self) -> &'static str {
        match self {
            Abilities::NONE => "",
            Abilities::ADAPTABILITY => "adaptability",
            Abilities::AERILATE => "aerilate",
            Abilities::AFTERMATH => "aftermath",
            Abilities::AIRLOCK => "airlock",
            Abilities::ANALYTIC => "analytic",
            Abilities::ANGERPOINT => "angerpoint",
            Abilities::ANGERSHELL => "angershell",
            Abilities::ANTICIPATION => "anticipation",
            Abilities::ARENATRAP => "arenatrap",
            Abilities::ARMORTAIL => "armortail",
            Abilities::AROMAVEIL => "aromaveil",
            Abilities::ASONEGLASTRIER => "asoneglastrier",
            Abilities::ASONESPECTRIER => "asonespectrier",
            Abilities::AURABREAK => "aurabreak",
            Abilities::BADDREAMS => "baddreams",
            Abilities::BALLFETCH => "ballfetch",
            Abilities::BATTERY => "battery",
            Abilities::BATTLEARMOR => "battlearmor",
            Abilities::BATTLEBOND => "battlebond",
            Abilities::BEADSOFRUIN => "beadsofruin",
            Abilities::BEASTBOOST => "beastboost",
            Abilities::BERSERK => "berserk",
            Abilities::BIGPECKS => "bigpecks",
            Abilities::BLAZE => "blaze",
            Abilities::BULLETPROOF => "bulletproof",
            Abilities::CHEEKPOUCH => "cheekpouch",
            Abilities::CHILLINGNEIGH => "chillingneigh",
            Abilities::CHLOROPHYLL => "chlorophyll",
            Abilities::CLEARBODY => "clearbody",
            Abilities::CLOUDNINE => "cloudnine",
            Abilities::COLORCHANGE => "colorchange",
            Abilities::COMATOSE => "comatose",
            Abilities::COMMANDER => "commander",
            Abilities::COMPETITIVE => "competitive",
            Abilities::COMPOUNDEYES => "compoundeyes",
            Abilities::CONTRARY => "contrary",
            Abilities::CORROSION => "corrosion",
            Abilities::COSTAR => "costar",
            Abilities::COTTONDOWN => "cottondown",
            Abilities::CUDCHEW => "cudchew",
            Abilities::CURIOUSMEDICINE => "curiousmedicine",
            Abilities::CURSEDBODY => "cursedbody",
            Abilities::CUTECHARM => "cutecharm",
            Abilities::DAMP => "damp",
            Abilities::DANCER => "dancer",
            Abilities::DARKAURA => "darkaura",
            Abilities::DAUNTLESSSHIELD => "dauntlessshield",
            Abilities::DAZZLING => "dazzling",
            Abilities::DEFEATIST => "defeatist",
            Abilities::DEFIANT => "defiant",
            Abilities::DELTASTREAM => "deltastream",
            Abilities::DESOLATELAND => "desolateland",
            Abilities::DISGUISE => "disguise",
            Abilities::DOWNLOAD => "download",
            Abilities::DRAGONSMAW => "dragonsmaw",
            Abilities::DRIZZLE => "drizzle",
            Abilities::DROUGHT => "drought",
            Abilities::DRYSKIN => "dryskin",
            Abilities::EARLYBIRD => "earlybird",
            Abilities::EARTHEATER => "eartheater",
            Abilities::EFFECTSPORE => "effectspore",
            Abilities::ELECTRICSURGE => "electricsurge",
            Abilities::ELECTROMORPHOSIS => "electromorphosis",
            Abilities::EMBODYASPECTCORNERSTONE => "embodyaspectcornerstone",
            Abilities::EMBODYASPECTHEARTHFLAME => "embodyaspecthearthflame",
            Abilities::EMBODYASPECTTEAL => "embodyaspectteal",
            Abilities::EMBODYASPECTWELLSPRING => "embodyaspectwellspring",
            Abilities::EMERGENCYEXIT => "emergencyexit",
            Abilities::FAIRYAURA => "fairyaura",
            Abilities::FILTER => "filter",
            Abilities::FLAMEBODY => "flamebody",
            Abilities::FLAREBOOST => "flareboost",
            Abilities::FLASHFIRE => "flashfire",
            Abilities::FLOWERGIFT => "flowergift",
            Abilities::FLOWERVEIL => "flowerveil",
            Abilities::FLUFFY => "fluffy",
            Abilities::FORECAST => "forecast",
            Abilities::FOREWARN => "forewarn",
            Abilities::FRIENDGUARD => "friendguard",
            Abilities::FRISK => "frisk",
            Abilities::FULLMETALBODY => "fullmetalbody",
            Abilities::FURCOAT => "furcoat",
            Abilities::GALEWINGS => "galewings",
            Abilities::GALVANIZE => "galvanize",
            Abilities::GLUTTONY => "gluttony",
            Abilities::GOODASGOLD => "goodasgold",
            Abilities::GOOEY => "gooey",
            Abilities::GORILLATACTICS => "gorillatactics",
            Abilities::GRASSPELT => "grasspelt",
            Abilities::GRASSYSURGE => "grassysurge",
            Abilities::GRIMNEIGH => "grimneigh",
            Abilities::GUARDDOG => "guarddog",
            Abilities::GULPMISSILE => "gulpmissile",
            Abilities::GUTS => "guts",
            Abilities::HADRONENGINE => "hadronengine",
            Abilities::HARVEST => "harvest",
            Abilities::HEALER => "healer",
            Abilities::HEATPROOF => "heatproof",
            Abilities::HEAVYMETAL => "heavymetal",
            Abilities::HONEYGATHER => "honeygather",
            Abilities::HOSPITALITY => "hospitality",
            Abilities::HUGEPOWER => "hugepower",
            Abilities::HUNGERSWITCH => "hungerswitch",
            Abilities::HUSTLE => "hustle",
            Abilities::HYDRATION => "hydration",
            Abilities::HYPERCUTTER => "hypercutter",
            Abilities::ICEBODY => "icebody",
            Abilities::ICEFACE => "iceface",
            Abilities::ICESCALES => "icescales",
            Abilities::ILLUMINATE => "illuminate",
            Abilities::ILLUSION => "illusion",
            Abilities::IMMUNITY => "immunity",
            Abilities::IMPOSTER => "imposter",
            Abilities::INFILTRATOR => "infiltrator",
            Abilities::INNARDSOUT => "innardsout",
            Abilities::INNERFOCUS => "innerfocus",
            Abilities::INSOMNIA => "insomnia",
            Abilities::INTIMIDATE => "intimidate",
            Abilities::INTREPIDSWORD => "intrepidsword",
            Abilities::IRONBARBS => "ironbarbs",
            Abilities::IRONFIST => "ironfist",
            Abilities::JUSTIFIED => "justified",
            Abilities::KEENEYE => "keeneye",
            Abilities::KLUTZ => "klutz",
            Abilities::LEAFGUARD => "leafguard",
            Abilities::LEVITATE => "levitate",
            Abilities::LIBERO => "libero",
            Abilities::LIGHTMETAL => "lightmetal",
            Abilities::LIGHTNINGROD => "lightningrod",
            Abilities::LIMBER => "limber",
            Abilities::LINGERINGAROMA => "lingeringaroma",
            Abilities::LIQUIDOOZE => "liquidooze",
            Abilities::LIQUIDVOICE => "liquidvoice",
            Abilities::LONGREACH => "longreach",
            Abilities::MAGICBOUNCE => "magicbounce",
            Abilities::MAGICGUARD => "magicguard",
            Abilities::MAGICIAN => "magician",
            Abilities::MAGMAARMOR => "magmaarmor",
            Abilities::MAGNETPULL => "magnetpull",
            Abilities::MARVELSCALE => "marvelscale",
            Abilities::MEGALAUNCHER => "megalauncher",
            Abilities::MERCILESS => "merciless",
            Abilities::MIMICRY => "mimicry",
            Abilities::MINDSEYE => "mindseye",
            Abilities::MINUS => "minus",
            Abilities::MIRRORARMOR => "mirrorarmor",
            Abilities::MISTYSURGE => "mistysurge",
            Abilities::MOLDBREAKER => "moldbreaker",
            Abilities::MOODY => "moody",
            Abilities::MOTORDRIVE => "motordrive",
            Abilities::MOUNTAINEER => "mountaineer",
            Abilities::MOXIE => "moxie",
            Abilities::MULTISCALE => "multiscale",
            Abilities::MULTITYPE => "multitype",
            Abilities::MUMMY => "mummy",
            Abilities::MYCELIUMMIGHT => "myceliummight",
            Abilities::NATURALCURE => "naturalcure",
            Abilities::NEUROFORCE => "neuroforce",
            Abilities::NEUTRALIZINGGAS => "neutralizinggas",
            Abilities::NOABILITY => "noability",
            Abilities::NOGUARD => "noguard",
            Abilities::NORMALIZE => "normalize",
            Abilities::OBLIVIOUS => "oblivious",
            Abilities::OPPORTUNIST => "opportunist",
            Abilities::ORICHALCUMPULSE => "orichalcumpulse",
            Abilities::OVERCOAT => "overcoat",
            Abilities::OVERGROW => "overgrow",
            Abilities::OWNTEMPO => "owntempo",
            Abilities::PARENTALBOND => "parentalbond",
            Abilities::PASTELVEIL => "pastelveil",
            Abilities::PERISHBODY => "perishbody",
            Abilities::PERSISTENT => "persistent",
            Abilities::PICKPOCKET => "pickpocket",
            Abilities::PICKUP => "pickup",
            Abilities::PIXILATE => "pixilate",
            Abilities::PLUS => "plus",
            Abilities::POISONHEAL => "poisonheal",
            Abilities::POISONPOINT => "poisonpoint",
            Abilities::POISONPUPPETEER => "poisonpuppeteer",
            Abilities::POISONTOUCH => "poisontouch",
            Abilities::POWERCONSTRUCT => "powerconstruct",
            Abilities::POWEROFALCHEMY => "powerofalchemy",
            Abilities::POWERSPOT => "powerspot",
            Abilities::PRANKSTER => "prankster",
            Abilities::PRESSURE => "pressure",
            Abilities::PRIMORDIALSEA => "primordialsea",
            Abilities::PRISMARMOR => "prismarmor",
            Abilities::PROPELLERTAIL => "propellertail",
            Abilities::PROTEAN => "protean",
            Abilities::PROTOSYNTHESIS => "protosynthesis",
            Abilities::PSYCHICSURGE => "psychicsurge",
            Abilities::PUNKROCK => "punkrock",
            Abilities::PUREPOWER => "purepower",
            Abilities::PURIFYINGSALT => "purifyingsalt",
            Abilities::QUARKDRIVE => "quarkdrive",
            Abilities::QUEENLYMAJESTY => "queenlymajesty",
            Abilities::QUICKDRAW => "quickdraw",
            Abilities::QUICKFEET => "quickfeet",
            Abilities::RAINDISH => "raindish",
            Abilities::RATTLED => "rattled",
            Abilities::REBOUND => "rebound",
            Abilities::RECEIVER => "receiver",
            Abilities::RECKLESS => "reckless",
            Abilities::REFRIGERATE => "refrigerate",
            Abilities::REGENERATOR => "regenerator",
            Abilities::RIPEN => "ripen",
            Abilities::RIVALRY => "rivalry",
            Abilities::RKSSYSTEM => "rkssystem",
            Abilities::ROCKHEAD => "rockhead",
            Abilities::ROCKYPAYLOAD => "rockypayload",
            Abilities::ROUGHSKIN => "roughskin",
            Abilities::RUNAWAY => "runaway",
            Abilities::SANDFORCE => "sandforce",
            Abilities::SANDRUSH => "sandrush",
            Abilities::SANDSPIT => "sandspit",
            Abilities::SANDSTREAM => "sandstream",
            Abilities::SANDVEIL => "sandveil",
            Abilities::SAPSIPPER => "sapsipper",
            Abilities::SCHOOLING => "schooling",
            Abilities::SCRAPPY => "scrappy",
            Abilities::SCREENCLEANER => "screencleaner",
            Abilities::SEEDSOWER => "seedsower",
            Abilities::SERENEGRACE => "serenegrace",
            Abilities::SHADOWSHIELD => "shadowshield",
            Abilities::SHADOWTAG => "shadowtag",
            Abilities::SHARPNESS => "sharpness",
            Abilities::SHEDSKIN => "shedskin",
            Abilities::SHEERFORCE => "sheerforce",
            Abilities::SHELLARMOR => "shellarmor",
            Abilities::SHIELDDUST => "shielddust",
            Abilities::SHIELDSDOWN => "shieldsdown",
            Abilities::SIMPLE => "simple",
            Abilities::SKILLLINK => "skilllink",
            Abilities::SLOWSTART => "slowstart",
            Abilities::SLUSHRUSH => "slushrush",
            Abilities::SNIPER => "sniper",
            Abilities::SNOWCLOAK => "snowcloak",
            Abilities::SNOWWARNING => "snowwarning",
            Abilities::SOLARPOWER => "solarpower",
            Abilities::SOLIDROCK => "solidrock",
            Abilities::SOULHEART => "soulheart",
            Abilities::SOUNDPROOF => "soundproof",
            Abilities::SPEEDBOOST => "speedboost",
            Abilities::STAKEOUT => "stakeout",
            Abilities::STALL => "stall",
            Abilities::STALWART => "stalwart",
            Abilities::STAMINA => "stamina",
            Abilities::STANCECHANGE => "stancechange",
            Abilities::STATIC => "static",
            Abilities::STEADFAST => "steadfast",
            Abilities::STEAMENGINE => "steamengine",
            Abilities::STEELWORKER => "steelworker",
            Abilities::STEELYSPIRIT => "steelyspirit",
            Abilities::STENCH => "stench",
            Abilities::STICKYHOLD => "stickyhold",
            Abilities::STORMDRAIN => "stormdrain",
            Abilities::STRONGJAW => "strongjaw",
            Abilities::STURDY => "sturdy",
            Abilities::SUCTIONCUPS => "suctioncups",
            Abilities::SUPERLUCK => "superluck",
            Abilities::SUPERSWEETSYRUP => "supersweetsyrup",
            Abilities::SUPREMEOVERLORD => "supremeoverlord",
            Abilities::SURGESURFER => "surgesurfer",
            Abilities::SWARM => "swarm",
            Abilities::SWEETVEIL => "sweetveil",
            Abilities::SWIFTSWIM => "swiftswim",
            Abilities::SWORDOFRUIN => "swordofruin",
            Abilities::SYMBIOSIS => "symbiosis",
            Abilities::SYNCHRONIZE => "synchronize",
            Abilities::TABLETSOFRUIN => "tabletsofruin",
            Abilities::TANGLEDFEET => "tangledfeet",
            Abilities::TANGLINGHAIR => "tanglinghair",
            Abilities::TECHNICIAN => "technician",
            Abilities::TELEPATHY => "telepathy",
            Abilities::TERAFORMZERO => "teraformzero",
            Abilities::TERASHELL => "terashell",
            Abilities::TERASHIFT => "terashift",
            Abilities::TERAVOLT => "teravolt",
            Abilities::THERMALEXCHANGE => "thermalexchange",
            Abilities::THICKFAT => "thickfat",
            Abilities::TINTEDLENS => "tintedlens",
            Abilities::TORRENT => "torrent",
            Abilities::TOUGHCLAWS => "toughclaws",
            Abilities::TOXICBOOST => "toxicboost",
            Abilities::TOXICCHAIN => "toxicchain",
            Abilities::TOXICDEBRIS => "toxicdebris",
            Abilities::TRACE => "trace",
            Abilities::TRANSISTOR => "transistor",
            Abilities::TRIAGE => "triage",
            Abilities::TRUANT => "truant",
            Abilities::TURBOBLAZE => "turboblaze",
            Abilities::UNAWARE => "unaware",
            Abilities::UNBURDEN => "unburden",
            Abilities::UNNERVE => "unnerve",
            Abilities::UNSEENFIST => "unseenfist",
            Abilities::VESSELOFRUIN => "vesselofruin",
            Abilities::VICTORYSTAR => "victorystar",
            Abilities::VITALSPIRIT => "vitalspirit",
            Abilities::VOLTABSORB => "voltabsorb",
            Abilities::WANDERINGSPIRIT => "wanderingspirit",
            Abilities::WATERABSORB => "waterabsorb",
            Abilities::WATERBUBBLE => "waterbubble",
            Abilities::WATERCOMPACTION => "watercompaction",
            Abilities::WATERVEIL => "waterveil",
            Abilities::WEAKARMOR => "weakarmor",
            Abilities::WELLBAKEDBODY => "wellbakedbody",
            Abilities::WHITESMOKE => "whitesmoke",
            Abilities::WIMPOUT => "wimpout",
            Abilities::WINDPOWER => "windpower",
            Abilities::WINDRIDER => "windrider",
            Abilities::WONDERGUARD => "wonderguard",
            Abilities::WONDERSKIN => "wonderskin",
            Abilities::ZENMODE => "zenmode",
            Abilities::ZEROTOHERO => "zerotohero",
        }
    }
    
    /// Get the display name of this abilities
    pub fn display_name(&self) -> &'static str {
        match self {
            Abilities::NONE => "None",
            Abilities::NOABILITY => "No Ability",
            Abilities::ADAPTABILITY => "Adaptability",
            Abilities::AERILATE => "Aerilate",
            Abilities::AFTERMATH => "Aftermath",
            Abilities::AIRLOCK => "Air Lock",
            Abilities::ANALYTIC => "Analytic",
            Abilities::ANGERPOINT => "Anger Point",
            Abilities::ANGERSHELL => "Anger Shell",
            Abilities::ANTICIPATION => "Anticipation",
            Abilities::ARENATRAP => "Arena Trap",
            Abilities::ARMORTAIL => "Armor Tail",
            Abilities::AROMAVEIL => "Aroma Veil",
            Abilities::ASONEGLASTRIER => "As One (Glastrier)",
            Abilities::ASONESPECTRIER => "As One (Spectrier)",
            Abilities::AURABREAK => "Aura Break",
            Abilities::BADDREAMS => "Bad Dreams",
            Abilities::BALLFETCH => "Ball Fetch",
            Abilities::BATTERY => "Battery",
            Abilities::BATTLEARMOR => "Battle Armor",
            Abilities::BATTLEBOND => "Battle Bond",
            Abilities::BEADSOFRUIN => "Beads of Ruin",
            Abilities::BEASTBOOST => "Beast Boost",
            Abilities::BERSERK => "Berserk",
            Abilities::BIGPECKS => "Big Pecks",
            Abilities::BLAZE => "Blaze",
            Abilities::BULLETPROOF => "Bulletproof",
            Abilities::CHEEKPOUCH => "Cheek Pouch",
            Abilities::CHILLINGNEIGH => "Chilling Neigh",
            Abilities::CHLOROPHYLL => "Chlorophyll",
            Abilities::CLEARBODY => "Clear Body",
            Abilities::CLOUDNINE => "Cloud Nine",
            Abilities::COLORCHANGE => "Color Change",
            Abilities::COMATOSE => "Comatose",
            Abilities::COMMANDER => "Commander",
            Abilities::COMPETITIVE => "Competitive",
            Abilities::COMPOUNDEYES => "Compound Eyes",
            Abilities::CONTRARY => "Contrary",
            Abilities::CORROSION => "Corrosion",
            Abilities::COSTAR => "Costar",
            Abilities::COTTONDOWN => "Cotton Down",
            Abilities::CUDCHEW => "Cud Chew",
            Abilities::CURIOUSMEDICINE => "Curious Medicine",
            Abilities::CURSEDBODY => "Cursed Body",
            Abilities::CUTECHARM => "Cute Charm",
            Abilities::DAMP => "Damp",
            Abilities::DANCER => "Dancer",
            Abilities::DARKAURA => "Dark Aura",
            Abilities::DAUNTLESSSHIELD => "Dauntless Shield",
            Abilities::DAZZLING => "Dazzling",
            Abilities::DEFEATIST => "Defeatist",
            Abilities::DEFIANT => "Defiant",
            Abilities::DELTASTREAM => "Delta Stream",
            Abilities::DESOLATELAND => "Desolate Land",
            Abilities::DISGUISE => "Disguise",
            Abilities::DOWNLOAD => "Download",
            Abilities::DRAGONSMAW => "Dragon's Maw",
            Abilities::DRIZZLE => "Drizzle",
            Abilities::DROUGHT => "Drought",
            Abilities::DRYSKIN => "Dry Skin",
            Abilities::EARLYBIRD => "Early Bird",
            Abilities::EARTHEATER => "Earth Eater",
            Abilities::EFFECTSPORE => "Effect Spore",
            Abilities::ELECTRICSURGE => "Electric Surge",
            Abilities::ELECTROMORPHOSIS => "Electromorphosis",
            Abilities::EMBODYASPECTCORNERSTONE => "Embody Aspect (Cornerstone)",
            Abilities::EMBODYASPECTHEARTHFLAME => "Embody Aspect (Hearthflame)",
            Abilities::EMBODYASPECTTEAL => "Embody Aspect (Teal)",
            Abilities::EMBODYASPECTWELLSPRING => "Embody Aspect (Wellspring)",
            Abilities::EMERGENCYEXIT => "Emergency Exit",
            Abilities::FAIRYAURA => "Fairy Aura",
            Abilities::FILTER => "Filter",
            Abilities::FLAMEBODY => "Flame Body",
            Abilities::FLAREBOOST => "Flare Boost",
            Abilities::FLASHFIRE => "Flash Fire",
            Abilities::FLOWERGIFT => "Flower Gift",
            Abilities::FLOWERVEIL => "Flower Veil",
            Abilities::FLUFFY => "Fluffy",
            Abilities::FORECAST => "Forecast",
            Abilities::FOREWARN => "Forewarn",
            Abilities::FRIENDGUARD => "Friend Guard",
            Abilities::FRISK => "Frisk",
            Abilities::FULLMETALBODY => "Full Metal Body",
            Abilities::FURCOAT => "Fur Coat",
            Abilities::GALEWINGS => "Gale Wings",
            Abilities::GALVANIZE => "Galvanize",
            Abilities::GLUTTONY => "Gluttony",
            Abilities::GOODASGOLD => "Good as Gold",
            Abilities::GOOEY => "Gooey",
            Abilities::GORILLATACTICS => "Gorilla Tactics",
            Abilities::GRASSPELT => "Grass Pelt",
            Abilities::GRASSYSURGE => "Grassy Surge",
            Abilities::GRIMNEIGH => "Grim Neigh",
            Abilities::GUARDDOG => "Guard Dog",
            Abilities::GULPMISSILE => "Gulp Missile",
            Abilities::GUTS => "Guts",
            Abilities::HADRONENGINE => "Hadron Engine",
            Abilities::HARVEST => "Harvest",
            Abilities::HEALER => "Healer",
            Abilities::HEATPROOF => "Heatproof",
            Abilities::HEAVYMETAL => "Heavy Metal",
            Abilities::HONEYGATHER => "Honey Gather",
            Abilities::HOSPITALITY => "Hospitality",
            Abilities::HUGEPOWER => "Huge Power",
            Abilities::HUNGERSWITCH => "Hunger Switch",
            Abilities::HUSTLE => "Hustle",
            Abilities::HYDRATION => "Hydration",
            Abilities::HYPERCUTTER => "Hyper Cutter",
            Abilities::ICEBODY => "Ice Body",
            Abilities::ICEFACE => "Ice Face",
            Abilities::ICESCALES => "Ice Scales",
            Abilities::ILLUMINATE => "Illuminate",
            Abilities::ILLUSION => "Illusion",
            Abilities::IMMUNITY => "Immunity",
            Abilities::IMPOSTER => "Imposter",
            Abilities::INFILTRATOR => "Infiltrator",
            Abilities::INNARDSOUT => "Innards Out",
            Abilities::INNERFOCUS => "Inner Focus",
            Abilities::INSOMNIA => "Insomnia",
            Abilities::INTIMIDATE => "Intimidate",
            Abilities::INTREPIDSWORD => "Intrepid Sword",
            Abilities::IRONBARBS => "Iron Barbs",
            Abilities::IRONFIST => "Iron Fist",
            Abilities::JUSTIFIED => "Justified",
            Abilities::KEENEYE => "Keen Eye",
            Abilities::KLUTZ => "Klutz",
            Abilities::LEAFGUARD => "Leaf Guard",
            Abilities::LEVITATE => "Levitate",
            Abilities::LIBERO => "Libero",
            Abilities::LIGHTMETAL => "Light Metal",
            Abilities::LIGHTNINGROD => "Lightning Rod",
            Abilities::LIMBER => "Limber",
            Abilities::LINGERINGAROMA => "Lingering Aroma",
            Abilities::LIQUIDOOZE => "Liquid Ooze",
            Abilities::LIQUIDVOICE => "Liquid Voice",
            Abilities::LONGREACH => "Long Reach",
            Abilities::MAGICBOUNCE => "Magic Bounce",
            Abilities::MAGICGUARD => "Magic Guard",
            Abilities::MAGICIAN => "Magician",
            Abilities::MAGMAARMOR => "Magma Armor",
            Abilities::MAGNETPULL => "Magnet Pull",
            Abilities::MARVELSCALE => "Marvel Scale",
            Abilities::MEGALAUNCHER => "Mega Launcher",
            Abilities::MERCILESS => "Merciless",
            Abilities::MIMICRY => "Mimicry",
            Abilities::MINDSEYE => "Mind's Eye",
            Abilities::MINUS => "Minus",
            Abilities::MIRRORARMOR => "Mirror Armor",
            Abilities::MISTYSURGE => "Misty Surge",
            Abilities::MOLDBREAKER => "Mold Breaker",
            Abilities::MOODY => "Moody",
            Abilities::MOTORDRIVE => "Motor Drive",
            Abilities::MOXIE => "Moxie",
            Abilities::MULTISCALE => "Multiscale",
            Abilities::MULTITYPE => "Multitype",
            Abilities::MUMMY => "Mummy",
            Abilities::MYCELIUMMIGHT => "Mycelium Might",
            Abilities::NATURALCURE => "Natural Cure",
            Abilities::NEUROFORCE => "Neuroforce",
            Abilities::NEUTRALIZINGGAS => "Neutralizing Gas",
            Abilities::NOGUARD => "No Guard",
            Abilities::NORMALIZE => "Normalize",
            Abilities::OBLIVIOUS => "Oblivious",
            Abilities::OPPORTUNIST => "Opportunist",
            Abilities::ORICHALCUMPULSE => "Orichalcum Pulse",
            Abilities::OVERCOAT => "Overcoat",
            Abilities::OVERGROW => "Overgrow",
            Abilities::OWNTEMPO => "Own Tempo",
            Abilities::PARENTALBOND => "Parental Bond",
            Abilities::PASTELVEIL => "Pastel Veil",
            Abilities::PERISHBODY => "Perish Body",
            Abilities::PICKPOCKET => "Pickpocket",
            Abilities::PICKUP => "Pickup",
            Abilities::PIXILATE => "Pixilate",
            Abilities::PLUS => "Plus",
            Abilities::POISONHEAL => "Poison Heal",
            Abilities::POISONPOINT => "Poison Point",
            Abilities::POISONPUPPETEER => "Poison Puppeteer",
            Abilities::POISONTOUCH => "Poison Touch",
            Abilities::POWERCONSTRUCT => "Power Construct",
            Abilities::POWEROFALCHEMY => "Power of Alchemy",
            Abilities::POWERSPOT => "Power Spot",
            Abilities::PRANKSTER => "Prankster",
            Abilities::PRESSURE => "Pressure",
            Abilities::PRIMORDIALSEA => "Primordial Sea",
            Abilities::PRISMARMOR => "Prism Armor",
            Abilities::PROPELLERTAIL => "Propeller Tail",
            Abilities::PROTEAN => "Protean",
            Abilities::PROTOSYNTHESIS => "Protosynthesis",
            Abilities::PSYCHICSURGE => "Psychic Surge",
            Abilities::PUNKROCK => "Punk Rock",
            Abilities::PUREPOWER => "Pure Power",
            Abilities::PURIFYINGSALT => "Purifying Salt",
            Abilities::QUARKDRIVE => "Quark Drive",
            Abilities::QUEENLYMAJESTY => "Queenly Majesty",
            Abilities::QUICKDRAW => "Quick Draw",
            Abilities::QUICKFEET => "Quick Feet",
            Abilities::RAINDISH => "Rain Dish",
            Abilities::RATTLED => "Rattled",
            Abilities::RECEIVER => "Receiver",
            Abilities::RECKLESS => "Reckless",
            Abilities::REFRIGERATE => "Refrigerate",
            Abilities::REGENERATOR => "Regenerator",
            Abilities::RIPEN => "Ripen",
            Abilities::RIVALRY => "Rivalry",
            Abilities::RKSSYSTEM => "RKS System",
            Abilities::ROCKHEAD => "Rock Head",
            Abilities::ROCKYPAYLOAD => "Rocky Payload",
            Abilities::ROUGHSKIN => "Rough Skin",
            Abilities::RUNAWAY => "Run Away",
            Abilities::SANDFORCE => "Sand Force",
            Abilities::SANDRUSH => "Sand Rush",
            Abilities::SANDSPIT => "Sand Spit",
            Abilities::SANDSTREAM => "Sand Stream",
            Abilities::SANDVEIL => "Sand Veil",
            Abilities::SAPSIPPER => "Sap Sipper",
            Abilities::SCHOOLING => "Schooling",
            Abilities::SCRAPPY => "Scrappy",
            Abilities::SCREENCLEANER => "Screen Cleaner",
            Abilities::SEEDSOWER => "Seed Sower",
            Abilities::SERENEGRACE => "Serene Grace",
            Abilities::SHADOWSHIELD => "Shadow Shield",
            Abilities::SHADOWTAG => "Shadow Tag",
            Abilities::SHARPNESS => "Sharpness",
            Abilities::SHEDSKIN => "Shed Skin",
            Abilities::SHEERFORCE => "Sheer Force",
            Abilities::SHELLARMOR => "Shell Armor",
            Abilities::SHIELDDUST => "Shield Dust",
            Abilities::SHIELDSDOWN => "Shields Down",
            Abilities::SIMPLE => "Simple",
            Abilities::SKILLLINK => "Skill Link",
            Abilities::SLOWSTART => "Slow Start",
            Abilities::SLUSHRUSH => "Slush Rush",
            Abilities::SNIPER => "Sniper",
            Abilities::SNOWCLOAK => "Snow Cloak",
            Abilities::SNOWWARNING => "Snow Warning",
            Abilities::SOLARPOWER => "Solar Power",
            Abilities::SOLIDROCK => "Solid Rock",
            Abilities::SOULHEART => "Soul-Heart",
            Abilities::SOUNDPROOF => "Soundproof",
            Abilities::SPEEDBOOST => "Speed Boost",
            Abilities::STAKEOUT => "Stakeout",
            Abilities::STALL => "Stall",
            Abilities::STALWART => "Stalwart",
            Abilities::STAMINA => "Stamina",
            Abilities::STANCECHANGE => "Stance Change",
            Abilities::STATIC => "Static",
            Abilities::STEADFAST => "Steadfast",
            Abilities::STEAMENGINE => "Steam Engine",
            Abilities::STEELWORKER => "Steelworker",
            Abilities::STEELYSPIRIT => "Steely Spirit",
            Abilities::STENCH => "Stench",
            Abilities::STICKYHOLD => "Sticky Hold",
            Abilities::STORMDRAIN => "Storm Drain",
            Abilities::STRONGJAW => "Strong Jaw",
            Abilities::STURDY => "Sturdy",
            Abilities::SUCTIONCUPS => "Suction Cups",
            Abilities::SUPERLUCK => "Super Luck",
            Abilities::SUPERSWEETSYRUP => "Supersweet Syrup",
            Abilities::SUPREMEOVERLORD => "Supreme Overlord",
            Abilities::SURGESURFER => "Surge Surfer",
            Abilities::SWARM => "Swarm",
            Abilities::SWEETVEIL => "Sweet Veil",
            Abilities::SWIFTSWIM => "Swift Swim",
            Abilities::SYMBIOSIS => "Symbiosis",
            Abilities::SYNCHRONIZE => "Synchronize",
            Abilities::SWORDOFRUIN => "Sword of Ruin",
            Abilities::TABLETSOFRUIN => "Tablets of Ruin",
            Abilities::TANGLEDFEET => "Tangled Feet",
            Abilities::TANGLINGHAIR => "Tangling Hair",
            Abilities::TECHNICIAN => "Technician",
            Abilities::TELEPATHY => "Telepathy",
            Abilities::TERAFORMZERO => "Teraform Zero",
            Abilities::TERASHELL => "Tera Shell",
            Abilities::TERASHIFT => "Tera Shift",
            Abilities::TERAVOLT => "Teravolt",
            Abilities::THERMALEXCHANGE => "Thermal Exchange",
            Abilities::THICKFAT => "Thick Fat",
            Abilities::TINTEDLENS => "Tinted Lens",
            Abilities::TORRENT => "Torrent",
            Abilities::TOUGHCLAWS => "Tough Claws",
            Abilities::TOXICBOOST => "Toxic Boost",
            Abilities::TOXICCHAIN => "Toxic Chain",
            Abilities::TOXICDEBRIS => "Toxic Debris",
            Abilities::TRACE => "Trace",
            Abilities::TRANSISTOR => "Transistor",
            Abilities::TRIAGE => "Triage",
            Abilities::TRUANT => "Truant",
            Abilities::TURBOBLAZE => "Turboblaze",
            Abilities::UNAWARE => "Unaware",
            Abilities::UNBURDEN => "Unburden",
            Abilities::UNNERVE => "Unnerve",
            Abilities::UNSEENFIST => "Unseen Fist",
            Abilities::VESSELOFRUIN => "Vessel of Ruin",
            Abilities::VICTORYSTAR => "Victory Star",
            Abilities::VITALSPIRIT => "Vital Spirit",
            Abilities::VOLTABSORB => "Volt Absorb",
            Abilities::WANDERINGSPIRIT => "Wandering Spirit",
            Abilities::WATERABSORB => "Water Absorb",
            Abilities::WATERBUBBLE => "Water Bubble",
            Abilities::WATERCOMPACTION => "Water Compaction",
            Abilities::WATERVEIL => "Water Veil",
            Abilities::WEAKARMOR => "Weak Armor",
            Abilities::WELLBAKEDBODY => "Well-Baked Body",
            Abilities::WHITESMOKE => "White Smoke",
            Abilities::WIMPOUT => "Wimp Out",
            Abilities::WINDPOWER => "Wind Power",
            Abilities::WINDRIDER => "Wind Rider",
            Abilities::WONDERGUARD => "Wonder Guard",
            Abilities::WONDERSKIN => "Wonder Skin",
            Abilities::ZENMODE => "Zen Mode",
            Abilities::ZEROTOHERO => "Zero to Hero",
            Abilities::MOUNTAINEER => "Mountaineer",
            Abilities::REBOUND => "Rebound",
            Abilities::PERSISTENT => "Persistent",
        }
    }
}

impl FromNormalizedString for Abilities {
    fn from_normalized_str(s: &str) -> Option<Self> {
        match s {
            "" => Some(Abilities::NONE),
            "noability" => Some(Abilities::NOABILITY),
            "adaptability" => Some(Abilities::ADAPTABILITY),
            "aerilate" => Some(Abilities::AERILATE),
            "aftermath" => Some(Abilities::AFTERMATH),
            "airlock" => Some(Abilities::AIRLOCK),
            "analytic" => Some(Abilities::ANALYTIC),
            "angerpoint" => Some(Abilities::ANGERPOINT),
            "angershell" => Some(Abilities::ANGERSHELL),
            "anticipation" => Some(Abilities::ANTICIPATION),
            "arenatrap" => Some(Abilities::ARENATRAP),
            "armortail" => Some(Abilities::ARMORTAIL),
            "aromaveil" => Some(Abilities::AROMAVEIL),
            "asoneglastrier" => Some(Abilities::ASONEGLASTRIER),
            "asonespectrier" => Some(Abilities::ASONESPECTRIER),
            "aurabreak" => Some(Abilities::AURABREAK),
            "baddreams" => Some(Abilities::BADDREAMS),
            "ballfetch" => Some(Abilities::BALLFETCH),
            "battery" => Some(Abilities::BATTERY),
            "battlearmor" => Some(Abilities::BATTLEARMOR),
            "battlebond" => Some(Abilities::BATTLEBOND),
            "beadsofruin" => Some(Abilities::BEADSOFRUIN),
            "beastboost" => Some(Abilities::BEASTBOOST),
            "berserk" => Some(Abilities::BERSERK),
            "bigpecks" => Some(Abilities::BIGPECKS),
            "blaze" => Some(Abilities::BLAZE),
            "bulletproof" => Some(Abilities::BULLETPROOF),
            "cheekpouch" => Some(Abilities::CHEEKPOUCH),
            "chillingneigh" => Some(Abilities::CHILLINGNEIGH),
            "chlorophyll" => Some(Abilities::CHLOROPHYLL),
            "clearbody" => Some(Abilities::CLEARBODY),
            "cloudnine" => Some(Abilities::CLOUDNINE),
            "colorchange" => Some(Abilities::COLORCHANGE),
            "comatose" => Some(Abilities::COMATOSE),
            "commander" => Some(Abilities::COMMANDER),
            "competitive" => Some(Abilities::COMPETITIVE),
            "compoundeyes" => Some(Abilities::COMPOUNDEYES),
            "contrary" => Some(Abilities::CONTRARY),
            "corrosion" => Some(Abilities::CORROSION),
            "costar" => Some(Abilities::COSTAR),
            "cottondown" => Some(Abilities::COTTONDOWN),
            "cudchew" => Some(Abilities::CUDCHEW),
            "curiousmedicine" => Some(Abilities::CURIOUSMEDICINE),
            "cursedbody" => Some(Abilities::CURSEDBODY),
            "cutecharm" => Some(Abilities::CUTECHARM),
            "damp" => Some(Abilities::DAMP),
            "dancer" => Some(Abilities::DANCER),
            "darkaura" => Some(Abilities::DARKAURA),
            "dauntlessshield" => Some(Abilities::DAUNTLESSSHIELD),
            "dazzling" => Some(Abilities::DAZZLING),
            "defeatist" => Some(Abilities::DEFEATIST),
            "defiant" => Some(Abilities::DEFIANT),
            "deltastream" => Some(Abilities::DELTASTREAM),
            "desolateland" => Some(Abilities::DESOLATELAND),
            "disguise" => Some(Abilities::DISGUISE),
            "download" => Some(Abilities::DOWNLOAD),
            "dragonsmaw" => Some(Abilities::DRAGONSMAW),
            "drizzle" => Some(Abilities::DRIZZLE),
            "drought" => Some(Abilities::DROUGHT),
            "dryskin" => Some(Abilities::DRYSKIN),
            "earlybird" => Some(Abilities::EARLYBIRD),
            "eartheater" => Some(Abilities::EARTHEATER),
            "effectspore" => Some(Abilities::EFFECTSPORE),
            "electricsurge" => Some(Abilities::ELECTRICSURGE),
            "electromorphosis" => Some(Abilities::ELECTROMORPHOSIS),
            "embodyaspectcornerstone" => Some(Abilities::EMBODYASPECTCORNERSTONE),
            "embodyaspecthearthflame" => Some(Abilities::EMBODYASPECTHEARTHFLAME),
            "embodyaspectteal" => Some(Abilities::EMBODYASPECTTEAL),
            "embodyaspectwellspring" => Some(Abilities::EMBODYASPECTWELLSPRING),
            "emergencyexit" => Some(Abilities::EMERGENCYEXIT),
            "fairyaura" => Some(Abilities::FAIRYAURA),
            "filter" => Some(Abilities::FILTER),
            "flamebody" => Some(Abilities::FLAMEBODY),
            "flareboost" => Some(Abilities::FLAREBOOST),
            "flashfire" => Some(Abilities::FLASHFIRE),
            "flowergift" => Some(Abilities::FLOWERGIFT),
            "flowerveil" => Some(Abilities::FLOWERVEIL),
            "fluffy" => Some(Abilities::FLUFFY),
            "forecast" => Some(Abilities::FORECAST),
            "forewarn" => Some(Abilities::FOREWARN),
            "friendguard" => Some(Abilities::FRIENDGUARD),
            "frisk" => Some(Abilities::FRISK),
            "fullmetalbody" => Some(Abilities::FULLMETALBODY),
            "furcoat" => Some(Abilities::FURCOAT),
            "galewings" => Some(Abilities::GALEWINGS),
            "galvanize" => Some(Abilities::GALVANIZE),
            "gluttony" => Some(Abilities::GLUTTONY),
            "goodasgold" => Some(Abilities::GOODASGOLD),
            "gooey" => Some(Abilities::GOOEY),
            "gorillatactics" => Some(Abilities::GORILLATACTICS),
            "grasspelt" => Some(Abilities::GRASSPELT),
            "grassysurge" => Some(Abilities::GRASSYSURGE),
            "grimneigh" => Some(Abilities::GRIMNEIGH),
            "guarddog" => Some(Abilities::GUARDDOG),
            "gulpmissile" => Some(Abilities::GULPMISSILE),
            "guts" => Some(Abilities::GUTS),
            "hadronengine" => Some(Abilities::HADRONENGINE),
            "harvest" => Some(Abilities::HARVEST),
            "healer" => Some(Abilities::HEALER),
            "heatproof" => Some(Abilities::HEATPROOF),
            "heavymetal" => Some(Abilities::HEAVYMETAL),
            "honeygather" => Some(Abilities::HONEYGATHER),
            "hospitality" => Some(Abilities::HOSPITALITY),
            "hugepower" => Some(Abilities::HUGEPOWER),
            "hungerswitch" => Some(Abilities::HUNGERSWITCH),
            "hustle" => Some(Abilities::HUSTLE),
            "hydration" => Some(Abilities::HYDRATION),
            "hypercutter" => Some(Abilities::HYPERCUTTER),
            "icebody" => Some(Abilities::ICEBODY),
            "iceface" => Some(Abilities::ICEFACE),
            "icescales" => Some(Abilities::ICESCALES),
            "illuminate" => Some(Abilities::ILLUMINATE),
            "illusion" => Some(Abilities::ILLUSION),
            "immunity" => Some(Abilities::IMMUNITY),
            "imposter" => Some(Abilities::IMPOSTER),
            "infiltrator" => Some(Abilities::INFILTRATOR),
            "innardsout" => Some(Abilities::INNARDSOUT),
            "innerfocus" => Some(Abilities::INNERFOCUS),
            "insomnia" => Some(Abilities::INSOMNIA),
            "intimidate" => Some(Abilities::INTIMIDATE),
            "intrepidsword" => Some(Abilities::INTREPIDSWORD),
            "ironbarbs" => Some(Abilities::IRONBARBS),
            "ironfist" => Some(Abilities::IRONFIST),
            "justified" => Some(Abilities::JUSTIFIED),
            "keeneye" => Some(Abilities::KEENEYE),
            "klutz" => Some(Abilities::KLUTZ),
            "leafguard" => Some(Abilities::LEAFGUARD),
            "levitate" => Some(Abilities::LEVITATE),
            "libero" => Some(Abilities::LIBERO),
            "lightmetal" => Some(Abilities::LIGHTMETAL),
            "lightningrod" => Some(Abilities::LIGHTNINGROD),
            "limber" => Some(Abilities::LIMBER),
            "lingeringaroma" => Some(Abilities::LINGERINGAROMA),
            "liquidooze" => Some(Abilities::LIQUIDOOZE),
            "liquidvoice" => Some(Abilities::LIQUIDVOICE),
            "longreach" => Some(Abilities::LONGREACH),
            "magicbounce" => Some(Abilities::MAGICBOUNCE),
            "magicguard" => Some(Abilities::MAGICGUARD),
            "magician" => Some(Abilities::MAGICIAN),
            "magmaarmor" => Some(Abilities::MAGMAARMOR),
            "magnetpull" => Some(Abilities::MAGNETPULL),
            "marvelscale" => Some(Abilities::MARVELSCALE),
            "megalauncher" => Some(Abilities::MEGALAUNCHER),
            "merciless" => Some(Abilities::MERCILESS),
            "mimicry" => Some(Abilities::MIMICRY),
            "mindseye" => Some(Abilities::MINDSEYE),
            "minus" => Some(Abilities::MINUS),
            "mirrorarmor" => Some(Abilities::MIRRORARMOR),
            "mistysurge" => Some(Abilities::MISTYSURGE),
            "moldbreaker" => Some(Abilities::MOLDBREAKER),
            "moody" => Some(Abilities::MOODY),
            "motordrive" => Some(Abilities::MOTORDRIVE),
            "moxie" => Some(Abilities::MOXIE),
            "multiscale" => Some(Abilities::MULTISCALE),
            "multitype" => Some(Abilities::MULTITYPE),
            "mummy" => Some(Abilities::MUMMY),
            "myceliummight" => Some(Abilities::MYCELIUMMIGHT),
            "naturalcure" => Some(Abilities::NATURALCURE),
            "neuroforce" => Some(Abilities::NEUROFORCE),
            "neutralizinggas" => Some(Abilities::NEUTRALIZINGGAS),
            "noguard" => Some(Abilities::NOGUARD),
            "normalize" => Some(Abilities::NORMALIZE),
            "oblivious" => Some(Abilities::OBLIVIOUS),
            "opportunist" => Some(Abilities::OPPORTUNIST),
            "orichalcumpulse" => Some(Abilities::ORICHALCUMPULSE),
            "overcoat" => Some(Abilities::OVERCOAT),
            "overgrow" => Some(Abilities::OVERGROW),
            "owntempo" => Some(Abilities::OWNTEMPO),
            "parentalbond" => Some(Abilities::PARENTALBOND),
            "pastelveil" => Some(Abilities::PASTELVEIL),
            "perishbody" => Some(Abilities::PERISHBODY),
            "pickpocket" => Some(Abilities::PICKPOCKET),
            "pickup" => Some(Abilities::PICKUP),
            "pixilate" => Some(Abilities::PIXILATE),
            "plus" => Some(Abilities::PLUS),
            "poisonheal" => Some(Abilities::POISONHEAL),
            "poisonpoint" => Some(Abilities::POISONPOINT),
            "poisonpuppeteer" => Some(Abilities::POISONPUPPETEER),
            "poisontouch" => Some(Abilities::POISONTOUCH),
            "powerconstruct" => Some(Abilities::POWERCONSTRUCT),
            "powerofalchemy" => Some(Abilities::POWEROFALCHEMY),
            "powerspot" => Some(Abilities::POWERSPOT),
            "prankster" => Some(Abilities::PRANKSTER),
            "pressure" => Some(Abilities::PRESSURE),
            "primordialsea" => Some(Abilities::PRIMORDIALSEA),
            "prismarmor" => Some(Abilities::PRISMARMOR),
            "propellertail" => Some(Abilities::PROPELLERTAIL),
            "protean" => Some(Abilities::PROTEAN),
            "protosynthesis" => Some(Abilities::PROTOSYNTHESIS),
            "psychicsurge" => Some(Abilities::PSYCHICSURGE),
            "punkrock" => Some(Abilities::PUNKROCK),
            "purepower" => Some(Abilities::PUREPOWER),
            "purifyingsalt" => Some(Abilities::PURIFYINGSALT),
            "quarkdrive" => Some(Abilities::QUARKDRIVE),
            "queenlymajesty" => Some(Abilities::QUEENLYMAJESTY),
            "quickdraw" => Some(Abilities::QUICKDRAW),
            "quickfeet" => Some(Abilities::QUICKFEET),
            "raindish" => Some(Abilities::RAINDISH),
            "rattled" => Some(Abilities::RATTLED),
            "receiver" => Some(Abilities::RECEIVER),
            "reckless" => Some(Abilities::RECKLESS),
            "refrigerate" => Some(Abilities::REFRIGERATE),
            "regenerator" => Some(Abilities::REGENERATOR),
            "ripen" => Some(Abilities::RIPEN),
            "rivalry" => Some(Abilities::RIVALRY),
            "rkssystem" => Some(Abilities::RKSSYSTEM),
            "rockhead" => Some(Abilities::ROCKHEAD),
            "rockypayload" => Some(Abilities::ROCKYPAYLOAD),
            "roughskin" => Some(Abilities::ROUGHSKIN),
            "runaway" => Some(Abilities::RUNAWAY),
            "sandforce" => Some(Abilities::SANDFORCE),
            "sandrush" => Some(Abilities::SANDRUSH),
            "sandspit" => Some(Abilities::SANDSPIT),
            "sandstream" => Some(Abilities::SANDSTREAM),
            "sandveil" => Some(Abilities::SANDVEIL),
            "sapsipper" => Some(Abilities::SAPSIPPER),
            "schooling" => Some(Abilities::SCHOOLING),
            "scrappy" => Some(Abilities::SCRAPPY),
            "screencleaner" => Some(Abilities::SCREENCLEANER),
            "seedsower" => Some(Abilities::SEEDSOWER),
            "serenegrace" => Some(Abilities::SERENEGRACE),
            "shadowshield" => Some(Abilities::SHADOWSHIELD),
            "shadowtag" => Some(Abilities::SHADOWTAG),
            "sharpness" => Some(Abilities::SHARPNESS),
            "shedskin" => Some(Abilities::SHEDSKIN),
            "sheerforce" => Some(Abilities::SHEERFORCE),
            "shellarmor" => Some(Abilities::SHELLARMOR),
            "shielddust" => Some(Abilities::SHIELDDUST),
            "shieldsdown" => Some(Abilities::SHIELDSDOWN),
            "simple" => Some(Abilities::SIMPLE),
            "skilllink" => Some(Abilities::SKILLLINK),
            "slowstart" => Some(Abilities::SLOWSTART),
            "slushrush" => Some(Abilities::SLUSHRUSH),
            "sniper" => Some(Abilities::SNIPER),
            "snowcloak" => Some(Abilities::SNOWCLOAK),
            "snowwarning" => Some(Abilities::SNOWWARNING),
            "solarpower" => Some(Abilities::SOLARPOWER),
            "solidrock" => Some(Abilities::SOLIDROCK),
            "soulheart" => Some(Abilities::SOULHEART),
            "soundproof" => Some(Abilities::SOUNDPROOF),
            "speedboost" => Some(Abilities::SPEEDBOOST),
            "stakeout" => Some(Abilities::STAKEOUT),
            "stall" => Some(Abilities::STALL),
            "stalwart" => Some(Abilities::STALWART),
            "stamina" => Some(Abilities::STAMINA),
            "stancechange" => Some(Abilities::STANCECHANGE),
            "static" => Some(Abilities::STATIC),
            "steadfast" => Some(Abilities::STEADFAST),
            "steamengine" => Some(Abilities::STEAMENGINE),
            "steelworker" => Some(Abilities::STEELWORKER),
            "steelyspirit" => Some(Abilities::STEELYSPIRIT),
            "stench" => Some(Abilities::STENCH),
            "stickyhold" => Some(Abilities::STICKYHOLD),
            "stormdrain" => Some(Abilities::STORMDRAIN),
            "strongjaw" => Some(Abilities::STRONGJAW),
            "sturdy" => Some(Abilities::STURDY),
            "suctioncups" => Some(Abilities::SUCTIONCUPS),
            "superluck" => Some(Abilities::SUPERLUCK),
            "supersweetsyrup" => Some(Abilities::SUPERSWEETSYRUP),
            "supremeoverlord" => Some(Abilities::SUPREMEOVERLORD),
            "surgesurfer" => Some(Abilities::SURGESURFER),
            "swarm" => Some(Abilities::SWARM),
            "sweetveil" => Some(Abilities::SWEETVEIL),
            "swiftswim" => Some(Abilities::SWIFTSWIM),
            "symbiosis" => Some(Abilities::SYMBIOSIS),
            "synchronize" => Some(Abilities::SYNCHRONIZE),
            "swordofruin" => Some(Abilities::SWORDOFRUIN),
            "tabletsofruin" => Some(Abilities::TABLETSOFRUIN),
            "tangledfeet" => Some(Abilities::TANGLEDFEET),
            "tanglinghair" => Some(Abilities::TANGLINGHAIR),
            "technician" => Some(Abilities::TECHNICIAN),
            "telepathy" => Some(Abilities::TELEPATHY),
            "teraformzero" => Some(Abilities::TERAFORMZERO),
            "terashell" => Some(Abilities::TERASHELL),
            "terashift" => Some(Abilities::TERASHIFT),
            "teravolt" => Some(Abilities::TERAVOLT),
            "thermalexchange" => Some(Abilities::THERMALEXCHANGE),
            "thickfat" => Some(Abilities::THICKFAT),
            "tintedlens" => Some(Abilities::TINTEDLENS),
            "torrent" => Some(Abilities::TORRENT),
            "toughclaws" => Some(Abilities::TOUGHCLAWS),
            "toxicboost" => Some(Abilities::TOXICBOOST),
            "toxicchain" => Some(Abilities::TOXICCHAIN),
            "toxicdebris" => Some(Abilities::TOXICDEBRIS),
            "trace" => Some(Abilities::TRACE),
            "transistor" => Some(Abilities::TRANSISTOR),
            "triage" => Some(Abilities::TRIAGE),
            "truant" => Some(Abilities::TRUANT),
            "turboblaze" => Some(Abilities::TURBOBLAZE),
            "unaware" => Some(Abilities::UNAWARE),
            "unburden" => Some(Abilities::UNBURDEN),
            "unnerve" => Some(Abilities::UNNERVE),
            "unseenfist" => Some(Abilities::UNSEENFIST),
            "vesselofruin" => Some(Abilities::VESSELOFRUIN),
            "victorystar" => Some(Abilities::VICTORYSTAR),
            "vitalspirit" => Some(Abilities::VITALSPIRIT),
            "voltabsorb" => Some(Abilities::VOLTABSORB),
            "wanderingspirit" => Some(Abilities::WANDERINGSPIRIT),
            "waterabsorb" => Some(Abilities::WATERABSORB),
            "waterbubble" => Some(Abilities::WATERBUBBLE),
            "watercompaction" => Some(Abilities::WATERCOMPACTION),
            "waterveil" => Some(Abilities::WATERVEIL),
            "weakarmor" => Some(Abilities::WEAKARMOR),
            "wellbakedbody" => Some(Abilities::WELLBAKEDBODY),
            "whitesmoke" => Some(Abilities::WHITESMOKE),
            "wimpout" => Some(Abilities::WIMPOUT),
            "windpower" => Some(Abilities::WINDPOWER),
            "windrider" => Some(Abilities::WINDRIDER),
            "wonderguard" => Some(Abilities::WONDERGUARD),
            "wonderskin" => Some(Abilities::WONDERSKIN),
            "zenmode" => Some(Abilities::ZENMODE),
            "zerotohero" => Some(Abilities::ZEROTOHERO),
            "mountaineer" => Some(Abilities::MOUNTAINEER),
            "rebound" => Some(Abilities::REBOUND),
            "persistent" => Some(Abilities::PERSISTENT),
            _ => None,
        }
    }
    
    fn valid_strings() -> Vec<&'static str> {
        vec![
            "noability",
            "adaptability",
            "aerilate",
            "aftermath",
            "airlock",
            "analytic",
            "angerpoint",
            "angershell",
            "anticipation",
            "arenatrap",
            "armortail",
            "aromaveil",
            "asoneglastrier",
            "asonespectrier",
            "aurabreak",
            "baddreams",
            "ballfetch",
            "battery",
            "battlearmor",
            "battlebond",
            "beadsofruin",
            "beastboost",
            "berserk",
            "bigpecks",
            "blaze",
            "bulletproof",
            "cheekpouch",
            "chillingneigh",
            "chlorophyll",
            "clearbody",
            "cloudnine",
            "colorchange",
            "comatose",
            "commander",
            "competitive",
            "compoundeyes",
            "contrary",
            "corrosion",
            "costar",
            "cottondown",
            "cudchew",
            "curiousmedicine",
            "cursedbody",
            "cutecharm",
            "damp",
            "dancer",
            "darkaura",
            "dauntlessshield",
            "dazzling",
            "defeatist",
            "defiant",
            "deltastream",
            "desolateland",
            "disguise",
            "download",
            "dragonsmaw",
            "drizzle",
            "drought",
            "dryskin",
            "earlybird",
            "eartheater",
            "effectspore",
            "electricsurge",
            "electromorphosis",
            "embodyaspectcornerstone",
            "embodyaspecthearthflame",
            "embodyaspectteal",
            "embodyaspectwellspring",
            "emergencyexit",
            "fairyaura",
            "filter",
            "flamebody",
            "flareboost",
            "flashfire",
            "flowergift",
            "flowerveil",
            "fluffy",
            "forecast",
            "forewarn",
            "friendguard",
            "frisk",
            "fullmetalbody",
            "furcoat",
            "galewings",
            "galvanize",
            "gluttony",
            "goodasgold",
            "gooey",
            "gorillatactics",
            "grasspelt",
            "grassysurge",
            "grimneigh",
            "guarddog",
            "gulpmissile",
            "guts",
            "hadronengine",
            "harvest",
            "healer",
            "heatproof",
            "heavymetal",
            "honeygather",
            "hospitality",
            "hugepower",
            "hungerswitch",
            "hustle",
            "hydration",
            "hypercutter",
            "icebody",
            "iceface",
            "icescales",
            "illuminate",
            "illusion",
            "immunity",
            "imposter",
            "infiltrator",
            "innardsout",
            "innerfocus",
            "insomnia",
            "intimidate",
            "intrepidsword",
            "ironbarbs",
            "ironfist",
            "justified",
            "keeneye",
            "klutz",
            "leafguard",
            "levitate",
            "libero",
            "lightmetal",
            "lightningrod",
            "limber",
            "lingeringaroma",
            "liquidooze",
            "liquidvoice",
            "longreach",
            "magicbounce",
            "magicguard",
            "magician",
            "magmaarmor",
            "magnetpull",
            "marvelscale",
            "megalauncher",
            "merciless",
            "mimicry",
            "mindseye",
            "minus",
            "mirrorarmor",
            "mistysurge",
            "moldbreaker",
            "moody",
            "motordrive",
            "moxie",
            "multiscale",
            "multitype",
            "mummy",
            "myceliummight",
            "naturalcure",
            "neuroforce",
            "neutralizinggas",
            "noguard",
            "normalize",
            "oblivious",
            "opportunist",
            "orichalcumpulse",
            "overcoat",
            "overgrow",
            "owntempo",
            "parentalbond",
            "pastelveil",
            "perishbody",
            "pickpocket",
            "pickup",
            "pixilate",
            "plus",
            "poisonheal",
            "poisonpoint",
            "poisonpuppeteer",
            "poisontouch",
            "powerconstruct",
            "powerofalchemy",
            "powerspot",
            "prankster",
            "pressure",
            "primordialsea",
            "prismarmor",
            "propellertail",
            "protean",
            "protosynthesis",
            "psychicsurge",
            "punkrock",
            "purepower",
            "purifyingsalt",
            "quarkdrive",
            "queenlymajesty",
            "quickdraw",
            "quickfeet",
            "raindish",
            "rattled",
            "receiver",
            "reckless",
            "refrigerate",
            "regenerator",
            "ripen",
            "rivalry",
            "rkssystem",
            "rockhead",
            "rockypayload",
            "roughskin",
            "runaway",
            "sandforce",
            "sandrush",
            "sandspit",
            "sandstream",
            "sandveil",
            "sapsipper",
            "schooling",
            "scrappy",
            "screencleaner",
            "seedsower",
            "serenegrace",
            "shadowshield",
            "shadowtag",
            "sharpness",
            "shedskin",
            "sheerforce",
            "shellarmor",
            "shielddust",
            "shieldsdown",
            "simple",
            "skilllink",
            "slowstart",
            "slushrush",
            "sniper",
            "snowcloak",
            "snowwarning",
            "solarpower",
            "solidrock",
            "soulheart",
            "soundproof",
            "speedboost",
            "stakeout",
            "stall",
            "stalwart",
            "stamina",
            "stancechange",
            "static",
            "steadfast",
            "steamengine",
            "steelworker",
            "steelyspirit",
            "stench",
            "stickyhold",
            "stormdrain",
            "strongjaw",
            "sturdy",
            "suctioncups",
            "superluck",
            "supersweetsyrup",
            "supremeoverlord",
            "surgesurfer",
            "swarm",
            "sweetveil",
            "swiftswim",
            "symbiosis",
            "synchronize",
            "swordofruin",
            "tabletsofruin",
            "tangledfeet",
            "tanglinghair",
            "technician",
            "telepathy",
            "teraformzero",
            "terashell",
            "terashift",
            "teravolt",
            "thermalexchange",
            "thickfat",
            "tintedlens",
            "torrent",
            "toughclaws",
            "toxicboost",
            "toxicchain",
            "toxicdebris",
            "trace",
            "transistor",
            "triage",
            "truant",
            "turboblaze",
            "unaware",
            "unburden",
            "unnerve",
            "unseenfist",
            "vesselofruin",
            "victorystar",
            "vitalspirit",
            "voltabsorb",
            "wanderingspirit",
            "waterabsorb",
            "waterbubble",
            "watercompaction",
            "waterveil",
            "weakarmor",
            "wellbakedbody",
            "whitesmoke",
            "wimpout",
            "windpower",
            "windrider",
            "wonderguard",
            "wonderskin",
            "zenmode",
            "zerotohero",
            "mountaineer",
            "rebound",
            "persistent",
        ]
    }
}

impl fmt::Display for Abilities {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.display_name())
    }
}

impl Default for Abilities {
    fn default() -> Self {
        Abilities::NONE
    }
}
