use serde::{Deserialize, Serialize};
use crate::types::from_string::FromNormalizedString;
use std::fmt;

/// Items enum with complete Pokemon Showdown data coverage
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Items {
    ABILITYSHIELD,
    ABOMASITE,
    ABSOLITE,
    ABSORBBULB,
    ADAMANTCRYSTAL,
    ADAMANTORB,
    ADRENALINEORB,
    AERODACTYLITE,
    AGGRONITE,
    AGUAVBERRY,
    AIRBALLOON,
    ALAKAZITE,
    ALORAICHIUMZ,
    ALTARIANITE,
    AMPHAROSITE,
    APICOTBERRY,
    ARMORFOSSIL,
    ASPEARBERRY,
    ASSAULTVEST,
    AUDINITE,
    AUSPICIOUSARMOR,
    BABIRIBERRY,
    BANETTITE,
    BEASTBALL,
    BEEDRILLITE,
    BELUEBERRY,
    BERRY,
    BERRYJUICE,
    BERRYSWEET,
    BERSERKGENE,
    BIGNUGGET,
    BIGROOT,
    BINDINGBAND,
    BITTERBERRY,
    BLACKBELT,
    BLACKGLASSES,
    BLACKSLUDGE,
    BLASTOISINITE,
    BLAZIKENITE,
    BLUEORB,
    BLUKBERRY,
    BLUNDERPOLICY,
    BOOSTERENERGY,
    BOTTLECAP,
    BRIGHTPOWDER,
    BUGGEM,
    BUGINIUMZ,
    BUGMEMORY,
    BURNDRIVE,
    BURNTBERRY,
    CAMERUPTITE,
    CELLBATTERY,
    CHARCOAL,
    CHARIZARDITEX,
    CHARIZARDITEY,
    CHARTIBERRY,
    CHERIBERRY,
    CHERISHBALL,
    CHESTOBERRY,
    CHILANBERRY,
    CHILLDRIVE,
    CHIPPEDPOT,
    CHOICEBAND,
    CHOICESCARF,
    CHOICESPECS,
    CHOPLEBERRY,
    CLAWFOSSIL,
    CLEARAMULET,
    CLOVERSWEET,
    COBABERRY,
    COLBURBERRY,
    CORNERSTONEMASK,
    CORNNBERRY,
    COVERFOSSIL,
    COVERTCLOAK,
    CRACKEDPOT,
    CRUCIBELLITE,
    CUSTAPBERRY,
    DAMPROCK,
    DARKGEM,
    DARKINIUMZ,
    DARKMEMORY,
    DAWNSTONE,
    DECIDIUMZ,
    DEEPSEASCALE,
    DEEPSEATOOTH,
    DESTINYKNOT,
    DIANCITE,
    DIVEBALL,
    DOMEFOSSIL,
    DOUSEDRIVE,
    DRACOPLATE,
    DRAGONFANG,
    DRAGONGEM,
    DRAGONIUMZ,
    DRAGONMEMORY,
    DRAGONSCALE,
    DREADPLATE,
    DREAMBALL,
    DUBIOUSDISC,
    DURINBERRY,
    DUSKBALL,
    DUSKSTONE,
    EARTHPLATE,
    EEVIUMZ,
    EJECTBUTTON,
    EJECTPACK,
    ELECTIRIZER,
    ELECTRICGEM,
    ELECTRICMEMORY,
    ELECTRICSEED,
    ELECTRIUMZ,
    ENIGMABERRY,
    EVIOLITE,
    EXPERTBELT,
    FAIRIUMZ,
    FAIRYFEATHER,
    FAIRYGEM,
    FAIRYMEMORY,
    FASTBALL,
    FIGHTINGGEM,
    FIGHTINGMEMORY,
    FIGHTINIUMZ,
    FIGYBERRY,
    FIREGEM,
    FIREMEMORY,
    FIRESTONE,
    FIRIUMZ,
    FISTPLATE,
    FLAMEORB,
    FLAMEPLATE,
    FLOATSTONE,
    FLOWERSWEET,
    FLYINGGEM,
    FLYINGMEMORY,
    FLYINIUMZ,
    FOCUSBAND,
    FOCUSSASH,
    FOSSILIZEDBIRD,
    FOSSILIZEDDINO,
    FOSSILIZEDDRAKE,
    FOSSILIZEDFISH,
    FRIENDBALL,
    FULLINCENSE,
    GALARICACUFF,
    GALARICAWREATH,
    GALLADITE,
    GANLONBERRY,
    GARCHOMPITE,
    GARDEVOIRITE,
    GENGARITE,
    GHOSTGEM,
    GHOSTIUMZ,
    GHOSTMEMORY,
    GLALITITE,
    GOLDBERRY,
    GOLDBOTTLECAP,
    GRASSGEM,
    GRASSIUMZ,
    GRASSMEMORY,
    GRASSYSEED,
    GREATBALL,
    GREPABERRY,
    GRIPCLAW,
    GRISEOUSCORE,
    GRISEOUSORB,
    GROUNDGEM,
    GROUNDIUMZ,
    GROUNDMEMORY,
    GYARADOSITE,
    HABANBERRY,
    HARDSTONE,
    HEALBALL,
    HEARTHFLAMEMASK,
    HEATROCK,
    HEAVYBALL,
    HEAVYDUTYBOOTS,
    HELIXFOSSIL,
    HERACRONITE,
    HONDEWBERRY,
    HOUNDOOMINITE,
    IAPAPABERRY,
    ICEBERRY,
    ICEGEM,
    ICEMEMORY,
    ICESTONE,
    ICICLEPLATE,
    ICIUMZ,
    ICYROCK,
    INCINIUMZ,
    INSECTPLATE,
    IRONBALL,
    IRONPLATE,
    JABOCABERRY,
    JAWFOSSIL,
    KANGASKHANITE,
    KASIBBERRY,
    KEBIABERRY,
    KEEBERRY,
    KELPSYBERRY,
    KINGSROCK,
    KOMMONIUMZ,
    LAGGINGTAIL,
    LANSATBERRY,
    LATIASITE,
    LATIOSITE,
    LAXINCENSE,
    LEAFSTONE,
    LEEK,
    LEFTOVERS,
    LEPPABERRY,
    LEVELBALL,
    LIECHIBERRY,
    LIFEORB,
    LIGHTBALL,
    LIGHTCLAY,
    LOADEDDICE,
    LOPUNNITE,
    LOVEBALL,
    LOVESWEET,
    LUCARIONITE,
    LUCKYPUNCH,
    LUMBERRY,
    LUMINOUSMOSS,
    LUNALIUMZ,
    LUREBALL,
    LUSTROUSGLOBE,
    LUSTROUSORB,
    LUXURYBALL,
    LYCANIUMZ,
    MACHOBRACE,
    MAGMARIZER,
    MAGNET,
    MAGOBERRY,
    MAGOSTBERRY,
    MAIL,
    MALICIOUSARMOR,
    MANECTITE,
    MARANGABERRY,
    MARSHADIUMZ,
    MASTERBALL,
    MASTERPIECETEACUP,
    MAWILITE,
    MEADOWPLATE,
    MEDICHAMITE,
    MENTALHERB,
    METAGROSSITE,
    METALALLOY,
    METALCOAT,
    METALPOWDER,
    METRONOME,
    MEWNIUMZ,
    MEWTWONITEX,
    MEWTWONITEY,
    MICLEBERRY,
    MIMIKIUMZ,
    MINDPLATE,
    MINTBERRY,
    MIRACLEBERRY,
    MIRACLESEED,
    MIRRORHERB,
    MISTYSEED,
    MOONBALL,
    MOONSTONE,
    MUSCLEBAND,
    MYSTERYBERRY,
    MYSTICWATER,
    NANABBERRY,
    NESTBALL,
    NETBALL,
    NEVERMELTICE,
    NOMELBERRY,
    NONE,
    NORMALGEM,
    NORMALIUMZ,
    OCCABERRY,
    ODDINCENSE,
    OLDAMBER,
    ORANBERRY,
    OVALSTONE,
    PAMTREBERRY,
    PARKBALL,
    PASSHOBERRY,
    PAYAPABERRY,
    PECHABERRY,
    PERSIMBERRY,
    PETAYABERRY,
    PIDGEOTITE,
    PIKANIUMZ,
    PIKASHUNIUMZ,
    PINAPBERRY,
    PINKBOW,
    PINSIRITE,
    PIXIEPLATE,
    PLUMEFOSSIL,
    POISONBARB,
    POISONGEM,
    POISONIUMZ,
    POISONMEMORY,
    POKEBALL,
    POLKADOTBOW,
    POMEGBERRY,
    POWERANKLET,
    POWERBAND,
    POWERBELT,
    POWERBRACER,
    POWERHERB,
    POWERLENS,
    POWERWEIGHT,
    PREMIERBALL,
    PRIMARIUMZ,
    PRISMSCALE,
    PROTECTIVEPADS,
    PROTECTOR,
    PRZCUREBERRY,
    PSNCUREBERRY,
    PSYCHICGEM,
    PSYCHICMEMORY,
    PSYCHICSEED,
    PSYCHIUMZ,
    PUNCHINGGLOVE,
    QUALOTBERRY,
    QUICKBALL,
    QUICKCLAW,
    QUICKPOWDER,
    RABUTABERRY,
    RAREBONE,
    RAWSTBERRY,
    RAZORCLAW,
    RAZORFANG,
    RAZZBERRY,
    REAPERCLOTH,
    REDCARD,
    REDORB,
    REPEATBALL,
    RIBBONSWEET,
    RINDOBERRY,
    RINGTARGET,
    ROCKGEM,
    ROCKINCENSE,
    ROCKIUMZ,
    ROCKMEMORY,
    ROCKYHELMET,
    ROOMSERVICE,
    ROOTFOSSIL,
    ROSEINCENSE,
    ROSELIBERRY,
    ROWAPBERRY,
    RUSTEDSHIELD,
    RUSTEDSWORD,
    SABLENITE,
    SACHET,
    SAFARIBALL,
    SAFETYGOGGLES,
    SAILFOSSIL,
    SALACBERRY,
    SALAMENCITE,
    SCEPTILITE,
    SCIZORITE,
    SCOPELENS,
    SEAINCENSE,
    SHARPBEAK,
    SHARPEDONITE,
    SHEDSHELL,
    SHELLBELL,
    SHINYSTONE,
    SHOCKDRIVE,
    SHUCABERRY,
    SILKSCARF,
    SILVERPOWDER,
    SITRUSBERRY,
    SKULLFOSSIL,
    SKYPLATE,
    SLOWBRONITE,
    SMOOTHROCK,
    SNORLIUMZ,
    SNOWBALL,
    SOFTSAND,
    SOLGANIUMZ,
    SOULDEW,
    SPELLTAG,
    SPELONBERRY,
    SPLASHPLATE,
    SPOOKYPLATE,
    SPORTBALL,
    STARFBERRY,
    STARSWEET,
    STEELGEM,
    STEELIUMZ,
    STEELIXITE,
    STEELMEMORY,
    STICK,
    STICKYBARB,
    STONEPLATE,
    STRANGEBALL,
    STRAWBERRYSWEET,
    SUNSTONE,
    SWAMPERTITE,
    SWEETAPPLE,
    SYRUPYAPPLE,
    TAMATOBERRY,
    TANGABERRY,
    TAPUNIUMZ,
    TARTAPPLE,
    TERRAINEXTENDER,
    THICKCLUB,
    THROATSPRAY,
    THUNDERSTONE,
    TIMERBALL,
    TOXICORB,
    TOXICPLATE,
    TR_00,
    TR_01,
    TR_02,
    TR_03,
    TR_04,
    TR_05,
    TR_06,
    TR_07,
    TR_08,
    TR_09,
    TR_10,
    TR_11,
    TR_12,
    TR_13,
    TR_14,
    TR_15,
    TR_16,
    TR_17,
    TR_18,
    TR_19,
    TR_20,
    TR_21,
    TR_22,
    TR_23,
    TR_24,
    TR_25,
    TR_26,
    TR_27,
    TR_28,
    TR_29,
    TR_30,
    TR_31,
    TR_32,
    TR_33,
    TR_34,
    TR_35,
    TR_36,
    TR_37,
    TR_38,
    TR_39,
    TR_40,
    TR_41,
    TR_42,
    TR_43,
    TR_44,
    TR_45,
    TR_46,
    TR_47,
    TR_48,
    TR_49,
    TR_50,
    TR_51,
    TR_52,
    TR_53,
    TR_54,
    TR_55,
    TR_56,
    TR_57,
    TR_58,
    TR_59,
    TR_60,
    TR_61,
    TR_62,
    TR_63,
    TR_64,
    TR_65,
    TR_66,
    TR_67,
    TR_68,
    TR_69,
    TR_70,
    TR_71,
    TR_72,
    TR_73,
    TR_74,
    TR_75,
    TR_76,
    TR_77,
    TR_78,
    TR_79,
    TR_80,
    TR_81,
    TR_82,
    TR_83,
    TR_84,
    TR_85,
    TR_86,
    TR_87,
    TR_88,
    TR_89,
    TR_90,
    TR_91,
    TR_92,
    TR_93,
    TR_94,
    TR_95,
    TR_96,
    TR_97,
    TR_98,
    TR_99,
    TWISTEDSPOON,
    TYRANITARITE,
    ULTRABALL,
    ULTRANECROZIUMZ,
    UNREMARKABLETEACUP,
    UPGRADE,
    UTILITYUMBRELLA,
    VENUSAURITE,
    VILEVIAL,
    WACANBERRY,
    WATERGEM,
    WATERIUMZ,
    WATERMEMORY,
    WATERSTONE,
    WATMELBERRY,
    WAVEINCENSE,
    WEAKNESSPOLICY,
    WELLSPRINGMASK,
    WEPEARBERRY,
    WHIPPEDDREAM,
    WHITEHERB,
    WIDELENS,
    WIKIBERRY,
    WISEGLASSES,
    YACHEBERRY,
    ZAPPLATE,
    ZOOMLENS,
}

impl Items {
    /// Get the normalized string representation of this items
    pub fn as_str(&self) -> &'static str {
        match self {
            Items::NONE => "",
            Items::ABILITYSHIELD => "abilityshield",
            Items::ABOMASITE => "abomasite",
            Items::ABSOLITE => "absolite",
            Items::ABSORBBULB => "absorbbulb",
            Items::ADAMANTCRYSTAL => "adamantcrystal",
            Items::ADAMANTORB => "adamantorb",
            Items::ADRENALINEORB => "adrenalineorb",
            Items::AERODACTYLITE => "aerodactylite",
            Items::AGGRONITE => "aggronite",
            Items::AGUAVBERRY => "aguavberry",
            Items::AIRBALLOON => "airballoon",
            Items::ALAKAZITE => "alakazite",
            Items::ALORAICHIUMZ => "aloraichiumz",
            Items::ALTARIANITE => "altarianite",
            Items::AMPHAROSITE => "ampharosite",
            Items::APICOTBERRY => "apicotberry",
            Items::ARMORFOSSIL => "armorfossil",
            Items::ASPEARBERRY => "aspearberry",
            Items::ASSAULTVEST => "assaultvest",
            Items::AUDINITE => "audinite",
            Items::AUSPICIOUSARMOR => "auspiciousarmor",
            Items::BABIRIBERRY => "babiriberry",
            Items::BANETTITE => "banettite",
            Items::BEASTBALL => "beastball",
            Items::BEEDRILLITE => "beedrillite",
            Items::BELUEBERRY => "belueberry",
            Items::BERRY => "berry",
            Items::BERRYJUICE => "berryjuice",
            Items::BERRYSWEET => "berrysweet",
            Items::BERSERKGENE => "berserkgene",
            Items::BIGNUGGET => "bignugget",
            Items::BIGROOT => "bigroot",
            Items::BINDINGBAND => "bindingband",
            Items::BITTERBERRY => "bitterberry",
            Items::BLACKBELT => "blackbelt",
            Items::BLACKGLASSES => "blackglasses",
            Items::BLACKSLUDGE => "blacksludge",
            Items::BLASTOISINITE => "blastoisinite",
            Items::BLAZIKENITE => "blazikenite",
            Items::BLUEORB => "blueorb",
            Items::BLUKBERRY => "blukberry",
            Items::BLUNDERPOLICY => "blunderpolicy",
            Items::BOOSTERENERGY => "boosterenergy",
            Items::BOTTLECAP => "bottlecap",
            Items::BRIGHTPOWDER => "brightpowder",
            Items::BUGGEM => "buggem",
            Items::BUGINIUMZ => "buginiumz",
            Items::BUGMEMORY => "bugmemory",
            Items::BURNDRIVE => "burndrive",
            Items::BURNTBERRY => "burntberry",
            Items::CAMERUPTITE => "cameruptite",
            Items::CELLBATTERY => "cellbattery",
            Items::CHARCOAL => "charcoal",
            Items::CHARIZARDITEX => "charizarditex",
            Items::CHARIZARDITEY => "charizarditey",
            Items::CHARTIBERRY => "chartiberry",
            Items::CHERIBERRY => "cheriberry",
            Items::CHERISHBALL => "cherishball",
            Items::CHESTOBERRY => "chestoberry",
            Items::CHILANBERRY => "chilanberry",
            Items::CHILLDRIVE => "chilldrive",
            Items::CHIPPEDPOT => "chippedpot",
            Items::CHOICEBAND => "choiceband",
            Items::CHOICESCARF => "choicescarf",
            Items::CHOICESPECS => "choicespecs",
            Items::CHOPLEBERRY => "chopleberry",
            Items::CLAWFOSSIL => "clawfossil",
            Items::CLEARAMULET => "clearamulet",
            Items::CLOVERSWEET => "cloversweet",
            Items::COBABERRY => "cobaberry",
            Items::COLBURBERRY => "colburberry",
            Items::CORNERSTONEMASK => "cornerstonemask",
            Items::CORNNBERRY => "cornnberry",
            Items::COVERFOSSIL => "coverfossil",
            Items::COVERTCLOAK => "covertcloak",
            Items::CRACKEDPOT => "crackedpot",
            Items::CRUCIBELLITE => "crucibellite",
            Items::CUSTAPBERRY => "custapberry",
            Items::DAMPROCK => "damprock",
            Items::DARKGEM => "darkgem",
            Items::DARKINIUMZ => "darkiniumz",
            Items::DARKMEMORY => "darkmemory",
            Items::DAWNSTONE => "dawnstone",
            Items::DECIDIUMZ => "decidiumz",
            Items::DEEPSEASCALE => "deepseascale",
            Items::DEEPSEATOOTH => "deepseatooth",
            Items::DESTINYKNOT => "destinyknot",
            Items::DIANCITE => "diancite",
            Items::DIVEBALL => "diveball",
            Items::DOMEFOSSIL => "domefossil",
            Items::DOUSEDRIVE => "dousedrive",
            Items::DRACOPLATE => "dracoplate",
            Items::DRAGONFANG => "dragonfang",
            Items::DRAGONGEM => "dragongem",
            Items::DRAGONIUMZ => "dragoniumz",
            Items::DRAGONMEMORY => "dragonmemory",
            Items::DRAGONSCALE => "dragonscale",
            Items::DREADPLATE => "dreadplate",
            Items::DREAMBALL => "dreamball",
            Items::DUBIOUSDISC => "dubiousdisc",
            Items::DURINBERRY => "durinberry",
            Items::DUSKBALL => "duskball",
            Items::DUSKSTONE => "duskstone",
            Items::EARTHPLATE => "earthplate",
            Items::EEVIUMZ => "eeviumz",
            Items::EJECTBUTTON => "ejectbutton",
            Items::EJECTPACK => "ejectpack",
            Items::ELECTIRIZER => "electirizer",
            Items::ELECTRICGEM => "electricgem",
            Items::ELECTRICMEMORY => "electricmemory",
            Items::ELECTRICSEED => "electricseed",
            Items::ELECTRIUMZ => "electriumz",
            Items::ENIGMABERRY => "enigmaberry",
            Items::EVIOLITE => "eviolite",
            Items::EXPERTBELT => "expertbelt",
            Items::FAIRIUMZ => "fairiumz",
            Items::FAIRYFEATHER => "fairyfeather",
            Items::FAIRYGEM => "fairygem",
            Items::FAIRYMEMORY => "fairymemory",
            Items::FASTBALL => "fastball",
            Items::FIGHTINGGEM => "fightinggem",
            Items::FIGHTINGMEMORY => "fightingmemory",
            Items::FIGHTINIUMZ => "fightiniumz",
            Items::FIGYBERRY => "figyberry",
            Items::FIREGEM => "firegem",
            Items::FIREMEMORY => "firememory",
            Items::FIRESTONE => "firestone",
            Items::FIRIUMZ => "firiumz",
            Items::FISTPLATE => "fistplate",
            Items::FLAMEORB => "flameorb",
            Items::FLAMEPLATE => "flameplate",
            Items::FLOATSTONE => "floatstone",
            Items::FLOWERSWEET => "flowersweet",
            Items::FLYINGGEM => "flyinggem",
            Items::FLYINGMEMORY => "flyingmemory",
            Items::FLYINIUMZ => "flyiniumz",
            Items::FOCUSBAND => "focusband",
            Items::FOCUSSASH => "focussash",
            Items::FOSSILIZEDBIRD => "fossilizedbird",
            Items::FOSSILIZEDDINO => "fossilizeddino",
            Items::FOSSILIZEDDRAKE => "fossilizeddrake",
            Items::FOSSILIZEDFISH => "fossilizedfish",
            Items::FRIENDBALL => "friendball",
            Items::FULLINCENSE => "fullincense",
            Items::GALARICACUFF => "galaricacuff",
            Items::GALARICAWREATH => "galaricawreath",
            Items::GALLADITE => "galladite",
            Items::GANLONBERRY => "ganlonberry",
            Items::GARCHOMPITE => "garchompite",
            Items::GARDEVOIRITE => "gardevoirite",
            Items::GENGARITE => "gengarite",
            Items::GHOSTGEM => "ghostgem",
            Items::GHOSTIUMZ => "ghostiumz",
            Items::GHOSTMEMORY => "ghostmemory",
            Items::GLALITITE => "glalitite",
            Items::GOLDBERRY => "goldberry",
            Items::GOLDBOTTLECAP => "goldbottlecap",
            Items::GRASSGEM => "grassgem",
            Items::GRASSIUMZ => "grassiumz",
            Items::GRASSMEMORY => "grassmemory",
            Items::GRASSYSEED => "grassyseed",
            Items::GREATBALL => "greatball",
            Items::GREPABERRY => "grepaberry",
            Items::GRIPCLAW => "gripclaw",
            Items::GRISEOUSCORE => "griseouscore",
            Items::GRISEOUSORB => "griseousorb",
            Items::GROUNDGEM => "groundgem",
            Items::GROUNDIUMZ => "groundiumz",
            Items::GROUNDMEMORY => "groundmemory",
            Items::GYARADOSITE => "gyaradosite",
            Items::HABANBERRY => "habanberry",
            Items::HARDSTONE => "hardstone",
            Items::HEALBALL => "healball",
            Items::HEARTHFLAMEMASK => "hearthflamemask",
            Items::HEATROCK => "heatrock",
            Items::HEAVYBALL => "heavyball",
            Items::HEAVYDUTYBOOTS => "heavydutyboots",
            Items::HELIXFOSSIL => "helixfossil",
            Items::HERACRONITE => "heracronite",
            Items::HONDEWBERRY => "hondewberry",
            Items::HOUNDOOMINITE => "houndoominite",
            Items::IAPAPABERRY => "iapapaberry",
            Items::ICEBERRY => "iceberry",
            Items::ICEGEM => "icegem",
            Items::ICEMEMORY => "icememory",
            Items::ICESTONE => "icestone",
            Items::ICICLEPLATE => "icicleplate",
            Items::ICIUMZ => "iciumz",
            Items::ICYROCK => "icyrock",
            Items::INCINIUMZ => "inciniumz",
            Items::INSECTPLATE => "insectplate",
            Items::IRONBALL => "ironball",
            Items::IRONPLATE => "ironplate",
            Items::JABOCABERRY => "jabocaberry",
            Items::JAWFOSSIL => "jawfossil",
            Items::KANGASKHANITE => "kangaskhanite",
            Items::KASIBBERRY => "kasibberry",
            Items::KEBIABERRY => "kebiaberry",
            Items::KEEBERRY => "keeberry",
            Items::KELPSYBERRY => "kelpsyberry",
            Items::KINGSROCK => "kingsrock",
            Items::KOMMONIUMZ => "kommoniumz",
            Items::LAGGINGTAIL => "laggingtail",
            Items::LANSATBERRY => "lansatberry",
            Items::LATIASITE => "latiasite",
            Items::LATIOSITE => "latiosite",
            Items::LAXINCENSE => "laxincense",
            Items::LEAFSTONE => "leafstone",
            Items::LEEK => "leek",
            Items::LEFTOVERS => "leftovers",
            Items::LEPPABERRY => "leppaberry",
            Items::LEVELBALL => "levelball",
            Items::LIECHIBERRY => "liechiberry",
            Items::LIFEORB => "lifeorb",
            Items::LIGHTBALL => "lightball",
            Items::LIGHTCLAY => "lightclay",
            Items::LOADEDDICE => "loadeddice",
            Items::LOPUNNITE => "lopunnite",
            Items::LOVEBALL => "loveball",
            Items::LOVESWEET => "lovesweet",
            Items::LUCARIONITE => "lucarionite",
            Items::LUCKYPUNCH => "luckypunch",
            Items::LUMBERRY => "lumberry",
            Items::LUMINOUSMOSS => "luminousmoss",
            Items::LUNALIUMZ => "lunaliumz",
            Items::LUREBALL => "lureball",
            Items::LUSTROUSGLOBE => "lustrousglobe",
            Items::LUSTROUSORB => "lustrousorb",
            Items::LUXURYBALL => "luxuryball",
            Items::LYCANIUMZ => "lycaniumz",
            Items::MACHOBRACE => "machobrace",
            Items::MAGMARIZER => "magmarizer",
            Items::MAGNET => "magnet",
            Items::MAGOBERRY => "magoberry",
            Items::MAGOSTBERRY => "magostberry",
            Items::MAIL => "mail",
            Items::MALICIOUSARMOR => "maliciousarmor",
            Items::MANECTITE => "manectite",
            Items::MARANGABERRY => "marangaberry",
            Items::MARSHADIUMZ => "marshadiumz",
            Items::MASTERBALL => "masterball",
            Items::MASTERPIECETEACUP => "masterpieceteacup",
            Items::MAWILITE => "mawilite",
            Items::MEADOWPLATE => "meadowplate",
            Items::MEDICHAMITE => "medichamite",
            Items::MENTALHERB => "mentalherb",
            Items::METAGROSSITE => "metagrossite",
            Items::METALALLOY => "metalalloy",
            Items::METALCOAT => "metalcoat",
            Items::METALPOWDER => "metalpowder",
            Items::METRONOME => "metronome",
            Items::MEWNIUMZ => "mewniumz",
            Items::MEWTWONITEX => "mewtwonitex",
            Items::MEWTWONITEY => "mewtwonitey",
            Items::MICLEBERRY => "micleberry",
            Items::MIMIKIUMZ => "mimikiumz",
            Items::MINDPLATE => "mindplate",
            Items::MINTBERRY => "mintberry",
            Items::MIRACLEBERRY => "miracleberry",
            Items::MIRACLESEED => "miracleseed",
            Items::MIRRORHERB => "mirrorherb",
            Items::MISTYSEED => "mistyseed",
            Items::MOONBALL => "moonball",
            Items::MOONSTONE => "moonstone",
            Items::MUSCLEBAND => "muscleband",
            Items::MYSTERYBERRY => "mysteryberry",
            Items::MYSTICWATER => "mysticwater",
            Items::NANABBERRY => "nanabberry",
            Items::NESTBALL => "nestball",
            Items::NETBALL => "netball",
            Items::NEVERMELTICE => "nevermeltice",
            Items::NOMELBERRY => "nomelberry",
            Items::NORMALGEM => "normalgem",
            Items::NORMALIUMZ => "normaliumz",
            Items::OCCABERRY => "occaberry",
            Items::ODDINCENSE => "oddincense",
            Items::OLDAMBER => "oldamber",
            Items::ORANBERRY => "oranberry",
            Items::OVALSTONE => "ovalstone",
            Items::PAMTREBERRY => "pamtreberry",
            Items::PARKBALL => "parkball",
            Items::PASSHOBERRY => "passhoberry",
            Items::PAYAPABERRY => "payapaberry",
            Items::PECHABERRY => "pechaberry",
            Items::PERSIMBERRY => "persimberry",
            Items::PETAYABERRY => "petayaberry",
            Items::PIDGEOTITE => "pidgeotite",
            Items::PIKANIUMZ => "pikaniumz",
            Items::PIKASHUNIUMZ => "pikashuniumz",
            Items::PINAPBERRY => "pinapberry",
            Items::PINKBOW => "pinkbow",
            Items::PINSIRITE => "pinsirite",
            Items::PIXIEPLATE => "pixieplate",
            Items::PLUMEFOSSIL => "plumefossil",
            Items::POISONBARB => "poisonbarb",
            Items::POISONGEM => "poisongem",
            Items::POISONIUMZ => "poisoniumz",
            Items::POISONMEMORY => "poisonmemory",
            Items::POKEBALL => "pokeball",
            Items::POLKADOTBOW => "polkadotbow",
            Items::POMEGBERRY => "pomegberry",
            Items::POWERANKLET => "poweranklet",
            Items::POWERBAND => "powerband",
            Items::POWERBELT => "powerbelt",
            Items::POWERBRACER => "powerbracer",
            Items::POWERHERB => "powerherb",
            Items::POWERLENS => "powerlens",
            Items::POWERWEIGHT => "powerweight",
            Items::PREMIERBALL => "premierball",
            Items::PRIMARIUMZ => "primariumz",
            Items::PRISMSCALE => "prismscale",
            Items::PROTECTIVEPADS => "protectivepads",
            Items::PROTECTOR => "protector",
            Items::PRZCUREBERRY => "przcureberry",
            Items::PSNCUREBERRY => "psncureberry",
            Items::PSYCHICGEM => "psychicgem",
            Items::PSYCHICMEMORY => "psychicmemory",
            Items::PSYCHICSEED => "psychicseed",
            Items::PSYCHIUMZ => "psychiumz",
            Items::PUNCHINGGLOVE => "punchingglove",
            Items::QUALOTBERRY => "qualotberry",
            Items::QUICKBALL => "quickball",
            Items::QUICKCLAW => "quickclaw",
            Items::QUICKPOWDER => "quickpowder",
            Items::RABUTABERRY => "rabutaberry",
            Items::RAREBONE => "rarebone",
            Items::RAWSTBERRY => "rawstberry",
            Items::RAZORCLAW => "razorclaw",
            Items::RAZORFANG => "razorfang",
            Items::RAZZBERRY => "razzberry",
            Items::REAPERCLOTH => "reapercloth",
            Items::REDCARD => "redcard",
            Items::REDORB => "redorb",
            Items::REPEATBALL => "repeatball",
            Items::RIBBONSWEET => "ribbonsweet",
            Items::RINDOBERRY => "rindoberry",
            Items::RINGTARGET => "ringtarget",
            Items::ROCKGEM => "rockgem",
            Items::ROCKINCENSE => "rockincense",
            Items::ROCKIUMZ => "rockiumz",
            Items::ROCKMEMORY => "rockmemory",
            Items::ROCKYHELMET => "rockyhelmet",
            Items::ROOMSERVICE => "roomservice",
            Items::ROOTFOSSIL => "rootfossil",
            Items::ROSEINCENSE => "roseincense",
            Items::ROSELIBERRY => "roseliberry",
            Items::ROWAPBERRY => "rowapberry",
            Items::RUSTEDSHIELD => "rustedshield",
            Items::RUSTEDSWORD => "rustedsword",
            Items::SABLENITE => "sablenite",
            Items::SACHET => "sachet",
            Items::SAFARIBALL => "safariball",
            Items::SAFETYGOGGLES => "safetygoggles",
            Items::SAILFOSSIL => "sailfossil",
            Items::SALACBERRY => "salacberry",
            Items::SALAMENCITE => "salamencite",
            Items::SCEPTILITE => "sceptilite",
            Items::SCIZORITE => "scizorite",
            Items::SCOPELENS => "scopelens",
            Items::SEAINCENSE => "seaincense",
            Items::SHARPBEAK => "sharpbeak",
            Items::SHARPEDONITE => "sharpedonite",
            Items::SHEDSHELL => "shedshell",
            Items::SHELLBELL => "shellbell",
            Items::SHINYSTONE => "shinystone",
            Items::SHOCKDRIVE => "shockdrive",
            Items::SHUCABERRY => "shucaberry",
            Items::SILKSCARF => "silkscarf",
            Items::SILVERPOWDER => "silverpowder",
            Items::SITRUSBERRY => "sitrusberry",
            Items::SKULLFOSSIL => "skullfossil",
            Items::SKYPLATE => "skyplate",
            Items::SLOWBRONITE => "slowbronite",
            Items::SMOOTHROCK => "smoothrock",
            Items::SNORLIUMZ => "snorliumz",
            Items::SNOWBALL => "snowball",
            Items::SOFTSAND => "softsand",
            Items::SOLGANIUMZ => "solganiumz",
            Items::SOULDEW => "souldew",
            Items::SPELLTAG => "spelltag",
            Items::SPELONBERRY => "spelonberry",
            Items::SPLASHPLATE => "splashplate",
            Items::SPOOKYPLATE => "spookyplate",
            Items::SPORTBALL => "sportball",
            Items::STARFBERRY => "starfberry",
            Items::STARSWEET => "starsweet",
            Items::STEELGEM => "steelgem",
            Items::STEELIUMZ => "steeliumz",
            Items::STEELIXITE => "steelixite",
            Items::STEELMEMORY => "steelmemory",
            Items::STICK => "stick",
            Items::STICKYBARB => "stickybarb",
            Items::STONEPLATE => "stoneplate",
            Items::STRANGEBALL => "strangeball",
            Items::STRAWBERRYSWEET => "strawberrysweet",
            Items::SUNSTONE => "sunstone",
            Items::SWAMPERTITE => "swampertite",
            Items::SWEETAPPLE => "sweetapple",
            Items::SYRUPYAPPLE => "syrupyapple",
            Items::TAMATOBERRY => "tamatoberry",
            Items::TANGABERRY => "tangaberry",
            Items::TAPUNIUMZ => "tapuniumz",
            Items::TARTAPPLE => "tartapple",
            Items::TERRAINEXTENDER => "terrainextender",
            Items::THICKCLUB => "thickclub",
            Items::THROATSPRAY => "throatspray",
            Items::THUNDERSTONE => "thunderstone",
            Items::TIMERBALL => "timerball",
            Items::TOXICORB => "toxicorb",
            Items::TOXICPLATE => "toxicplate",
            Items::TR_00 => "tr00",
            Items::TR_01 => "tr01",
            Items::TR_02 => "tr02",
            Items::TR_03 => "tr03",
            Items::TR_04 => "tr04",
            Items::TR_05 => "tr05",
            Items::TR_06 => "tr06",
            Items::TR_07 => "tr07",
            Items::TR_08 => "tr08",
            Items::TR_09 => "tr09",
            Items::TR_10 => "tr10",
            Items::TR_11 => "tr11",
            Items::TR_12 => "tr12",
            Items::TR_13 => "tr13",
            Items::TR_14 => "tr14",
            Items::TR_15 => "tr15",
            Items::TR_16 => "tr16",
            Items::TR_17 => "tr17",
            Items::TR_18 => "tr18",
            Items::TR_19 => "tr19",
            Items::TR_20 => "tr20",
            Items::TR_21 => "tr21",
            Items::TR_22 => "tr22",
            Items::TR_23 => "tr23",
            Items::TR_24 => "tr24",
            Items::TR_25 => "tr25",
            Items::TR_26 => "tr26",
            Items::TR_27 => "tr27",
            Items::TR_28 => "tr28",
            Items::TR_29 => "tr29",
            Items::TR_30 => "tr30",
            Items::TR_31 => "tr31",
            Items::TR_32 => "tr32",
            Items::TR_33 => "tr33",
            Items::TR_34 => "tr34",
            Items::TR_35 => "tr35",
            Items::TR_36 => "tr36",
            Items::TR_37 => "tr37",
            Items::TR_38 => "tr38",
            Items::TR_39 => "tr39",
            Items::TR_40 => "tr40",
            Items::TR_41 => "tr41",
            Items::TR_42 => "tr42",
            Items::TR_43 => "tr43",
            Items::TR_44 => "tr44",
            Items::TR_45 => "tr45",
            Items::TR_46 => "tr46",
            Items::TR_47 => "tr47",
            Items::TR_48 => "tr48",
            Items::TR_49 => "tr49",
            Items::TR_50 => "tr50",
            Items::TR_51 => "tr51",
            Items::TR_52 => "tr52",
            Items::TR_53 => "tr53",
            Items::TR_54 => "tr54",
            Items::TR_55 => "tr55",
            Items::TR_56 => "tr56",
            Items::TR_57 => "tr57",
            Items::TR_58 => "tr58",
            Items::TR_59 => "tr59",
            Items::TR_60 => "tr60",
            Items::TR_61 => "tr61",
            Items::TR_62 => "tr62",
            Items::TR_63 => "tr63",
            Items::TR_64 => "tr64",
            Items::TR_65 => "tr65",
            Items::TR_66 => "tr66",
            Items::TR_67 => "tr67",
            Items::TR_68 => "tr68",
            Items::TR_69 => "tr69",
            Items::TR_70 => "tr70",
            Items::TR_71 => "tr71",
            Items::TR_72 => "tr72",
            Items::TR_73 => "tr73",
            Items::TR_74 => "tr74",
            Items::TR_75 => "tr75",
            Items::TR_76 => "tr76",
            Items::TR_77 => "tr77",
            Items::TR_78 => "tr78",
            Items::TR_79 => "tr79",
            Items::TR_80 => "tr80",
            Items::TR_81 => "tr81",
            Items::TR_82 => "tr82",
            Items::TR_83 => "tr83",
            Items::TR_84 => "tr84",
            Items::TR_85 => "tr85",
            Items::TR_86 => "tr86",
            Items::TR_87 => "tr87",
            Items::TR_88 => "tr88",
            Items::TR_89 => "tr89",
            Items::TR_90 => "tr90",
            Items::TR_91 => "tr91",
            Items::TR_92 => "tr92",
            Items::TR_93 => "tr93",
            Items::TR_94 => "tr94",
            Items::TR_95 => "tr95",
            Items::TR_96 => "tr96",
            Items::TR_97 => "tr97",
            Items::TR_98 => "tr98",
            Items::TR_99 => "tr99",
            Items::TWISTEDSPOON => "twistedspoon",
            Items::TYRANITARITE => "tyranitarite",
            Items::ULTRABALL => "ultraball",
            Items::ULTRANECROZIUMZ => "ultranecroziumz",
            Items::UNREMARKABLETEACUP => "unremarkableteacup",
            Items::UPGRADE => "upgrade",
            Items::UTILITYUMBRELLA => "utilityumbrella",
            Items::VENUSAURITE => "venusaurite",
            Items::VILEVIAL => "vilevial",
            Items::WACANBERRY => "wacanberry",
            Items::WATERGEM => "watergem",
            Items::WATERIUMZ => "wateriumz",
            Items::WATERMEMORY => "watermemory",
            Items::WATERSTONE => "waterstone",
            Items::WATMELBERRY => "watmelberry",
            Items::WAVEINCENSE => "waveincense",
            Items::WEAKNESSPOLICY => "weaknesspolicy",
            Items::WELLSPRINGMASK => "wellspringmask",
            Items::WEPEARBERRY => "wepearberry",
            Items::WHIPPEDDREAM => "whippeddream",
            Items::WHITEHERB => "whiteherb",
            Items::WIDELENS => "widelens",
            Items::WIKIBERRY => "wikiberry",
            Items::WISEGLASSES => "wiseglasses",
            Items::YACHEBERRY => "yacheberry",
            Items::ZAPPLATE => "zapplate",
            Items::ZOOMLENS => "zoomlens",
        }
    }
    
    /// Get the display name of this items
    pub fn display_name(&self) -> &'static str {
        match self {
            Items::NONE => "None",
            Items::ABILITYSHIELD => "Ability Shield",
            Items::ABOMASITE => "Abomasite",
            Items::ABSOLITE => "Absolite",
            Items::ABSORBBULB => "Absorb Bulb",
            Items::ADAMANTCRYSTAL => "Adamant Crystal",
            Items::ADAMANTORB => "Adamant Orb",
            Items::ADRENALINEORB => "Adrenaline Orb",
            Items::AERODACTYLITE => "Aerodactylite",
            Items::AGGRONITE => "Aggronite",
            Items::AGUAVBERRY => "Aguav Berry",
            Items::AIRBALLOON => "Air Balloon",
            Items::ALAKAZITE => "Alakazite",
            Items::ALORAICHIUMZ => "Aloraichium Z",
            Items::ALTARIANITE => "Altarianite",
            Items::AMPHAROSITE => "Ampharosite",
            Items::APICOTBERRY => "Apicot Berry",
            Items::ARMORFOSSIL => "Armor Fossil",
            Items::ASPEARBERRY => "Aspear Berry",
            Items::ASSAULTVEST => "Assault Vest",
            Items::AUDINITE => "Audinite",
            Items::AUSPICIOUSARMOR => "Auspicious Armor",
            Items::BABIRIBERRY => "Babiri Berry",
            Items::BANETTITE => "Banettite",
            Items::BEASTBALL => "Beast Ball",
            Items::BEEDRILLITE => "Beedrillite",
            Items::BELUEBERRY => "Belue Berry",
            Items::BERRYJUICE => "Berry Juice",
            Items::BERRYSWEET => "Berry Sweet",
            Items::BIGNUGGET => "Big Nugget",
            Items::BIGROOT => "Big Root",
            Items::BINDINGBAND => "Binding Band",
            Items::BLACKBELT => "Black Belt",
            Items::BLACKGLASSES => "Black Glasses",
            Items::BLACKSLUDGE => "Black Sludge",
            Items::BLASTOISINITE => "Blastoisinite",
            Items::BLAZIKENITE => "Blazikenite",
            Items::BLUEORB => "Blue Orb",
            Items::BLUKBERRY => "Bluk Berry",
            Items::BLUNDERPOLICY => "Blunder Policy",
            Items::BOOSTERENERGY => "Booster Energy",
            Items::BOTTLECAP => "Bottle Cap",
            Items::BRIGHTPOWDER => "Bright Powder",
            Items::BUGGEM => "Bug Gem",
            Items::BUGMEMORY => "Bug Memory",
            Items::BUGINIUMZ => "Buginium Z",
            Items::BURNDRIVE => "Burn Drive",
            Items::CAMERUPTITE => "Cameruptite",
            Items::CELLBATTERY => "Cell Battery",
            Items::CHARCOAL => "Charcoal",
            Items::CHARIZARDITEX => "Charizardite X",
            Items::CHARIZARDITEY => "Charizardite Y",
            Items::CHARTIBERRY => "Charti Berry",
            Items::CHERIBERRY => "Cheri Berry",
            Items::CHERISHBALL => "Cherish Ball",
            Items::CHESTOBERRY => "Chesto Berry",
            Items::CHILANBERRY => "Chilan Berry",
            Items::CHILLDRIVE => "Chill Drive",
            Items::CHIPPEDPOT => "Chipped Pot",
            Items::CHOICEBAND => "Choice Band",
            Items::CHOICESCARF => "Choice Scarf",
            Items::CHOICESPECS => "Choice Specs",
            Items::CHOPLEBERRY => "Chople Berry",
            Items::CLAWFOSSIL => "Claw Fossil",
            Items::CLEARAMULET => "Clear Amulet",
            Items::CLOVERSWEET => "Clover Sweet",
            Items::COBABERRY => "Coba Berry",
            Items::COLBURBERRY => "Colbur Berry",
            Items::CORNERSTONEMASK => "Cornerstone Mask",
            Items::CORNNBERRY => "Cornn Berry",
            Items::COVERFOSSIL => "Cover Fossil",
            Items::COVERTCLOAK => "Covert Cloak",
            Items::CRACKEDPOT => "Cracked Pot",
            Items::CUSTAPBERRY => "Custap Berry",
            Items::DAMPROCK => "Damp Rock",
            Items::DARKGEM => "Dark Gem",
            Items::DARKMEMORY => "Dark Memory",
            Items::DARKINIUMZ => "Darkinium Z",
            Items::DAWNSTONE => "Dawn Stone",
            Items::DECIDIUMZ => "Decidium Z",
            Items::DEEPSEASCALE => "Deep Sea Scale",
            Items::DEEPSEATOOTH => "Deep Sea Tooth",
            Items::DESTINYKNOT => "Destiny Knot",
            Items::DIANCITE => "Diancite",
            Items::DIVEBALL => "Dive Ball",
            Items::DOMEFOSSIL => "Dome Fossil",
            Items::DOUSEDRIVE => "Douse Drive",
            Items::DRACOPLATE => "Draco Plate",
            Items::DRAGONFANG => "Dragon Fang",
            Items::DRAGONGEM => "Dragon Gem",
            Items::DRAGONMEMORY => "Dragon Memory",
            Items::DRAGONSCALE => "Dragon Scale",
            Items::DRAGONIUMZ => "Dragonium Z",
            Items::DREADPLATE => "Dread Plate",
            Items::DREAMBALL => "Dream Ball",
            Items::DUBIOUSDISC => "Dubious Disc",
            Items::DURINBERRY => "Durin Berry",
            Items::DUSKBALL => "Dusk Ball",
            Items::DUSKSTONE => "Dusk Stone",
            Items::EARTHPLATE => "Earth Plate",
            Items::EEVIUMZ => "Eevium Z",
            Items::EJECTBUTTON => "Eject Button",
            Items::EJECTPACK => "Eject Pack",
            Items::ELECTIRIZER => "Electirizer",
            Items::ELECTRICGEM => "Electric Gem",
            Items::ELECTRICMEMORY => "Electric Memory",
            Items::ELECTRICSEED => "Electric Seed",
            Items::ELECTRIUMZ => "Electrium Z",
            Items::ENIGMABERRY => "Enigma Berry",
            Items::EVIOLITE => "Eviolite",
            Items::EXPERTBELT => "Expert Belt",
            Items::FAIRIUMZ => "Fairium Z",
            Items::FAIRYFEATHER => "Fairy Feather",
            Items::FAIRYGEM => "Fairy Gem",
            Items::FAIRYMEMORY => "Fairy Memory",
            Items::FASTBALL => "Fast Ball",
            Items::FIGHTINGGEM => "Fighting Gem",
            Items::FIGHTINGMEMORY => "Fighting Memory",
            Items::FIGHTINIUMZ => "Fightinium Z",
            Items::FIGYBERRY => "Figy Berry",
            Items::FIREGEM => "Fire Gem",
            Items::FIREMEMORY => "Fire Memory",
            Items::FIRESTONE => "Fire Stone",
            Items::FIRIUMZ => "Firium Z",
            Items::FISTPLATE => "Fist Plate",
            Items::FLAMEORB => "Flame Orb",
            Items::FLAMEPLATE => "Flame Plate",
            Items::FLOATSTONE => "Float Stone",
            Items::FLOWERSWEET => "Flower Sweet",
            Items::FLYINGGEM => "Flying Gem",
            Items::FLYINGMEMORY => "Flying Memory",
            Items::FLYINIUMZ => "Flyinium Z",
            Items::FOCUSBAND => "Focus Band",
            Items::FOCUSSASH => "Focus Sash",
            Items::FOSSILIZEDBIRD => "Fossilized Bird",
            Items::FOSSILIZEDDINO => "Fossilized Dino",
            Items::FOSSILIZEDDRAKE => "Fossilized Drake",
            Items::FOSSILIZEDFISH => "Fossilized Fish",
            Items::FRIENDBALL => "Friend Ball",
            Items::FULLINCENSE => "Full Incense",
            Items::GALARICACUFF => "Galarica Cuff",
            Items::GALARICAWREATH => "Galarica Wreath",
            Items::GALLADITE => "Galladite",
            Items::GANLONBERRY => "Ganlon Berry",
            Items::GARCHOMPITE => "Garchompite",
            Items::GARDEVOIRITE => "Gardevoirite",
            Items::GENGARITE => "Gengarite",
            Items::GHOSTGEM => "Ghost Gem",
            Items::GHOSTMEMORY => "Ghost Memory",
            Items::GHOSTIUMZ => "Ghostium Z",
            Items::GLALITITE => "Glalitite",
            Items::GOLDBOTTLECAP => "Gold Bottle Cap",
            Items::GRASSGEM => "Grass Gem",
            Items::GRASSMEMORY => "Grass Memory",
            Items::GRASSIUMZ => "Grassium Z",
            Items::GRASSYSEED => "Grassy Seed",
            Items::GREATBALL => "Great Ball",
            Items::GREPABERRY => "Grepa Berry",
            Items::GRIPCLAW => "Grip Claw",
            Items::GRISEOUSCORE => "Griseous Core",
            Items::GRISEOUSORB => "Griseous Orb",
            Items::GROUNDGEM => "Ground Gem",
            Items::GROUNDMEMORY => "Ground Memory",
            Items::GROUNDIUMZ => "Groundium Z",
            Items::GYARADOSITE => "Gyaradosite",
            Items::HABANBERRY => "Haban Berry",
            Items::HARDSTONE => "Hard Stone",
            Items::HEALBALL => "Heal Ball",
            Items::HEARTHFLAMEMASK => "Hearthflame Mask",
            Items::HEATROCK => "Heat Rock",
            Items::HEAVYBALL => "Heavy Ball",
            Items::HEAVYDUTYBOOTS => "Heavy-Duty Boots",
            Items::HELIXFOSSIL => "Helix Fossil",
            Items::HERACRONITE => "Heracronite",
            Items::HONDEWBERRY => "Hondew Berry",
            Items::HOUNDOOMINITE => "Houndoominite",
            Items::IAPAPABERRY => "Iapapa Berry",
            Items::ICEGEM => "Ice Gem",
            Items::ICEMEMORY => "Ice Memory",
            Items::ICESTONE => "Ice Stone",
            Items::ICICLEPLATE => "Icicle Plate",
            Items::ICIUMZ => "Icium Z",
            Items::ICYROCK => "Icy Rock",
            Items::INCINIUMZ => "Incinium Z",
            Items::INSECTPLATE => "Insect Plate",
            Items::IRONBALL => "Iron Ball",
            Items::IRONPLATE => "Iron Plate",
            Items::JABOCABERRY => "Jaboca Berry",
            Items::JAWFOSSIL => "Jaw Fossil",
            Items::KASIBBERRY => "Kasib Berry",
            Items::KEBIABERRY => "Kebia Berry",
            Items::KEEBERRY => "Kee Berry",
            Items::KELPSYBERRY => "Kelpsy Berry",
            Items::KANGASKHANITE => "Kangaskhanite",
            Items::KINGSROCK => "King's Rock",
            Items::KOMMONIUMZ => "Kommonium Z",
            Items::LAGGINGTAIL => "Lagging Tail",
            Items::LANSATBERRY => "Lansat Berry",
            Items::LATIASITE => "Latiasite",
            Items::LATIOSITE => "Latiosite",
            Items::LAXINCENSE => "Lax Incense",
            Items::LEAFSTONE => "Leaf Stone",
            Items::LEEK => "Leek",
            Items::LEFTOVERS => "Leftovers",
            Items::LEPPABERRY => "Leppa Berry",
            Items::LEVELBALL => "Level Ball",
            Items::LIECHIBERRY => "Liechi Berry",
            Items::LIFEORB => "Life Orb",
            Items::LIGHTBALL => "Light Ball",
            Items::LIGHTCLAY => "Light Clay",
            Items::LOADEDDICE => "Loaded Dice",
            Items::LOPUNNITE => "Lopunnite",
            Items::LOVEBALL => "Love Ball",
            Items::LOVESWEET => "Love Sweet",
            Items::LUCARIONITE => "Lucarionite",
            Items::LUCKYPUNCH => "Lucky Punch",
            Items::LUMBERRY => "Lum Berry",
            Items::LUMINOUSMOSS => "Luminous Moss",
            Items::LUNALIUMZ => "Lunalium Z",
            Items::LUREBALL => "Lure Ball",
            Items::LUSTROUSGLOBE => "Lustrous Globe",
            Items::LUSTROUSORB => "Lustrous Orb",
            Items::LUXURYBALL => "Luxury Ball",
            Items::LYCANIUMZ => "Lycanium Z",
            Items::MACHOBRACE => "Macho Brace",
            Items::MAGMARIZER => "Magmarizer",
            Items::MAGNET => "Magnet",
            Items::MAGOBERRY => "Mago Berry",
            Items::MAGOSTBERRY => "Magost Berry",
            Items::MAIL => "Mail",
            Items::MALICIOUSARMOR => "Malicious Armor",
            Items::MANECTITE => "Manectite",
            Items::MARANGABERRY => "Maranga Berry",
            Items::MARSHADIUMZ => "Marshadium Z",
            Items::MASTERBALL => "Master Ball",
            Items::MASTERPIECETEACUP => "Masterpiece Teacup",
            Items::MAWILITE => "Mawilite",
            Items::MEADOWPLATE => "Meadow Plate",
            Items::MEDICHAMITE => "Medichamite",
            Items::MENTALHERB => "Mental Herb",
            Items::METAGROSSITE => "Metagrossite",
            Items::METALALLOY => "Metal Alloy",
            Items::METALCOAT => "Metal Coat",
            Items::METALPOWDER => "Metal Powder",
            Items::METRONOME => "Metronome",
            Items::MEWNIUMZ => "Mewnium Z",
            Items::MEWTWONITEX => "Mewtwonite X",
            Items::MEWTWONITEY => "Mewtwonite Y",
            Items::MICLEBERRY => "Micle Berry",
            Items::MIMIKIUMZ => "Mimikium Z",
            Items::MINDPLATE => "Mind Plate",
            Items::MIRACLESEED => "Miracle Seed",
            Items::MIRRORHERB => "Mirror Herb",
            Items::MISTYSEED => "Misty Seed",
            Items::MOONBALL => "Moon Ball",
            Items::MOONSTONE => "Moon Stone",
            Items::MUSCLEBAND => "Muscle Band",
            Items::MYSTICWATER => "Mystic Water",
            Items::NANABBERRY => "Nanab Berry",
            Items::NESTBALL => "Nest Ball",
            Items::NETBALL => "Net Ball",
            Items::NEVERMELTICE => "Never-Melt Ice",
            Items::NOMELBERRY => "Nomel Berry",
            Items::NORMALGEM => "Normal Gem",
            Items::NORMALIUMZ => "Normalium Z",
            Items::OCCABERRY => "Occa Berry",
            Items::ODDINCENSE => "Odd Incense",
            Items::OLDAMBER => "Old Amber",
            Items::ORANBERRY => "Oran Berry",
            Items::OVALSTONE => "Oval Stone",
            Items::PAMTREBERRY => "Pamtre Berry",
            Items::PARKBALL => "Park Ball",
            Items::PASSHOBERRY => "Passho Berry",
            Items::PAYAPABERRY => "Payapa Berry",
            Items::PECHABERRY => "Pecha Berry",
            Items::PERSIMBERRY => "Persim Berry",
            Items::PETAYABERRY => "Petaya Berry",
            Items::PIDGEOTITE => "Pidgeotite",
            Items::PIKANIUMZ => "Pikanium Z",
            Items::PIKASHUNIUMZ => "Pikashunium Z",
            Items::PINAPBERRY => "Pinap Berry",
            Items::PINSIRITE => "Pinsirite",
            Items::PIXIEPLATE => "Pixie Plate",
            Items::PLUMEFOSSIL => "Plume Fossil",
            Items::POISONBARB => "Poison Barb",
            Items::POISONGEM => "Poison Gem",
            Items::POISONMEMORY => "Poison Memory",
            Items::POISONIUMZ => "Poisonium Z",
            Items::POKEBALL => "Poke Ball",
            Items::POMEGBERRY => "Pomeg Berry",
            Items::POWERANKLET => "Power Anklet",
            Items::POWERBAND => "Power Band",
            Items::POWERBELT => "Power Belt",
            Items::POWERBRACER => "Power Bracer",
            Items::POWERHERB => "Power Herb",
            Items::POWERLENS => "Power Lens",
            Items::POWERWEIGHT => "Power Weight",
            Items::PREMIERBALL => "Premier Ball",
            Items::PRIMARIUMZ => "Primarium Z",
            Items::PRISMSCALE => "Prism Scale",
            Items::PROTECTIVEPADS => "Protective Pads",
            Items::PROTECTOR => "Protector",
            Items::PSYCHICGEM => "Psychic Gem",
            Items::PSYCHICMEMORY => "Psychic Memory",
            Items::PSYCHICSEED => "Psychic Seed",
            Items::PSYCHIUMZ => "Psychium Z",
            Items::PUNCHINGGLOVE => "Punching Glove",
            Items::QUALOTBERRY => "Qualot Berry",
            Items::QUICKBALL => "Quick Ball",
            Items::QUICKCLAW => "Quick Claw",
            Items::QUICKPOWDER => "Quick Powder",
            Items::RABUTABERRY => "Rabuta Berry",
            Items::RAREBONE => "Rare Bone",
            Items::RAWSTBERRY => "Rawst Berry",
            Items::RAZORCLAW => "Razor Claw",
            Items::RAZORFANG => "Razor Fang",
            Items::RAZZBERRY => "Razz Berry",
            Items::REAPERCLOTH => "Reaper Cloth",
            Items::REDCARD => "Red Card",
            Items::REDORB => "Red Orb",
            Items::REPEATBALL => "Repeat Ball",
            Items::RIBBONSWEET => "Ribbon Sweet",
            Items::RINDOBERRY => "Rindo Berry",
            Items::RINGTARGET => "Ring Target",
            Items::ROCKGEM => "Rock Gem",
            Items::ROCKINCENSE => "Rock Incense",
            Items::ROCKMEMORY => "Rock Memory",
            Items::ROCKIUMZ => "Rockium Z",
            Items::ROCKYHELMET => "Rocky Helmet",
            Items::ROOMSERVICE => "Room Service",
            Items::ROOTFOSSIL => "Root Fossil",
            Items::ROSEINCENSE => "Rose Incense",
            Items::ROSELIBERRY => "Roseli Berry",
            Items::ROWAPBERRY => "Rowap Berry",
            Items::RUSTEDSHIELD => "Rusted Shield",
            Items::RUSTEDSWORD => "Rusted Sword",
            Items::SABLENITE => "Sablenite",
            Items::SACHET => "Sachet",
            Items::SAFARIBALL => "Safari Ball",
            Items::SAFETYGOGGLES => "Safety Goggles",
            Items::SAILFOSSIL => "Sail Fossil",
            Items::SALACBERRY => "Salac Berry",
            Items::SALAMENCITE => "Salamencite",
            Items::SCEPTILITE => "Sceptilite",
            Items::SCIZORITE => "Scizorite",
            Items::SCOPELENS => "Scope Lens",
            Items::SEAINCENSE => "Sea Incense",
            Items::SHARPBEAK => "Sharp Beak",
            Items::SHARPEDONITE => "Sharpedonite",
            Items::SHEDSHELL => "Shed Shell",
            Items::SHELLBELL => "Shell Bell",
            Items::SHINYSTONE => "Shiny Stone",
            Items::SHOCKDRIVE => "Shock Drive",
            Items::SHUCABERRY => "Shuca Berry",
            Items::SILKSCARF => "Silk Scarf",
            Items::SILVERPOWDER => "Silver Powder",
            Items::SITRUSBERRY => "Sitrus Berry",
            Items::SKULLFOSSIL => "Skull Fossil",
            Items::SKYPLATE => "Sky Plate",
            Items::SLOWBRONITE => "Slowbronite",
            Items::SMOOTHROCK => "Smooth Rock",
            Items::SNORLIUMZ => "Snorlium Z",
            Items::SNOWBALL => "Snowball",
            Items::SOFTSAND => "Soft Sand",
            Items::SOLGANIUMZ => "Solganium Z",
            Items::SOULDEW => "Soul Dew",
            Items::SPELLTAG => "Spell Tag",
            Items::SPELONBERRY => "Spelon Berry",
            Items::SPLASHPLATE => "Splash Plate",
            Items::SPOOKYPLATE => "Spooky Plate",
            Items::SPORTBALL => "Sport Ball",
            Items::STARFBERRY => "Starf Berry",
            Items::STARSWEET => "Star Sweet",
            Items::STEELIXITE => "Steelixite",
            Items::STEELGEM => "Steel Gem",
            Items::STEELMEMORY => "Steel Memory",
            Items::STEELIUMZ => "Steelium Z",
            Items::STICK => "Stick",
            Items::STICKYBARB => "Sticky Barb",
            Items::STONEPLATE => "Stone Plate",
            Items::STRANGEBALL => "Strange Ball",
            Items::STRAWBERRYSWEET => "Strawberry Sweet",
            Items::SUNSTONE => "Sun Stone",
            Items::SWAMPERTITE => "Swampertite",
            Items::SWEETAPPLE => "Sweet Apple",
            Items::SYRUPYAPPLE => "Syrupy Apple",
            Items::TAMATOBERRY => "Tamato Berry",
            Items::TANGABERRY => "Tanga Berry",
            Items::TAPUNIUMZ => "Tapunium Z",
            Items::TARTAPPLE => "Tart Apple",
            Items::TERRAINEXTENDER => "Terrain Extender",
            Items::THICKCLUB => "Thick Club",
            Items::THROATSPRAY => "Throat Spray",
            Items::THUNDERSTONE => "Thunder Stone",
            Items::TIMERBALL => "Timer Ball",
            Items::TOXICORB => "Toxic Orb",
            Items::TOXICPLATE => "Toxic Plate",
            Items::TR_00 => "TR00",
            Items::TR_01 => "TR01",
            Items::TR_02 => "TR02",
            Items::TR_03 => "TR03",
            Items::TR_04 => "TR04",
            Items::TR_05 => "TR05",
            Items::TR_06 => "TR06",
            Items::TR_07 => "TR07",
            Items::TR_08 => "TR08",
            Items::TR_09 => "TR09",
            Items::TR_10 => "TR10",
            Items::TR_11 => "TR11",
            Items::TR_12 => "TR12",
            Items::TR_13 => "TR13",
            Items::TR_14 => "TR14",
            Items::TR_15 => "TR15",
            Items::TR_16 => "TR16",
            Items::TR_17 => "TR17",
            Items::TR_18 => "TR18",
            Items::TR_19 => "TR19",
            Items::TR_20 => "TR20",
            Items::TR_21 => "TR21",
            Items::TR_22 => "TR22",
            Items::TR_23 => "TR23",
            Items::TR_24 => "TR24",
            Items::TR_25 => "TR25",
            Items::TR_26 => "TR26",
            Items::TR_27 => "TR27",
            Items::TR_28 => "TR28",
            Items::TR_29 => "TR29",
            Items::TR_30 => "TR30",
            Items::TR_31 => "TR31",
            Items::TR_32 => "TR32",
            Items::TR_33 => "TR33",
            Items::TR_34 => "TR34",
            Items::TR_35 => "TR35",
            Items::TR_36 => "TR36",
            Items::TR_37 => "TR37",
            Items::TR_38 => "TR38",
            Items::TR_39 => "TR39",
            Items::TR_40 => "TR40",
            Items::TR_41 => "TR41",
            Items::TR_42 => "TR42",
            Items::TR_43 => "TR43",
            Items::TR_44 => "TR44",
            Items::TR_45 => "TR45",
            Items::TR_46 => "TR46",
            Items::TR_47 => "TR47",
            Items::TR_48 => "TR48",
            Items::TR_49 => "TR49",
            Items::TR_50 => "TR50",
            Items::TR_51 => "TR51",
            Items::TR_52 => "TR52",
            Items::TR_53 => "TR53",
            Items::TR_54 => "TR54",
            Items::TR_55 => "TR55",
            Items::TR_56 => "TR56",
            Items::TR_57 => "TR57",
            Items::TR_58 => "TR58",
            Items::TR_59 => "TR59",
            Items::TR_60 => "TR60",
            Items::TR_61 => "TR61",
            Items::TR_62 => "TR62",
            Items::TR_63 => "TR63",
            Items::TR_64 => "TR64",
            Items::TR_65 => "TR65",
            Items::TR_66 => "TR66",
            Items::TR_67 => "TR67",
            Items::TR_68 => "TR68",
            Items::TR_69 => "TR69",
            Items::TR_70 => "TR70",
            Items::TR_71 => "TR71",
            Items::TR_72 => "TR72",
            Items::TR_73 => "TR73",
            Items::TR_74 => "TR74",
            Items::TR_75 => "TR75",
            Items::TR_76 => "TR76",
            Items::TR_77 => "TR77",
            Items::TR_78 => "TR78",
            Items::TR_79 => "TR79",
            Items::TR_80 => "TR80",
            Items::TR_81 => "TR81",
            Items::TR_82 => "TR82",
            Items::TR_83 => "TR83",
            Items::TR_84 => "TR84",
            Items::TR_85 => "TR85",
            Items::TR_86 => "TR86",
            Items::TR_87 => "TR87",
            Items::TR_88 => "TR88",
            Items::TR_89 => "TR89",
            Items::TR_90 => "TR90",
            Items::TR_91 => "TR91",
            Items::TR_92 => "TR92",
            Items::TR_93 => "TR93",
            Items::TR_94 => "TR94",
            Items::TR_95 => "TR95",
            Items::TR_96 => "TR96",
            Items::TR_97 => "TR97",
            Items::TR_98 => "TR98",
            Items::TR_99 => "TR99",
            Items::TWISTEDSPOON => "Twisted Spoon",
            Items::TYRANITARITE => "Tyranitarite",
            Items::ULTRABALL => "Ultra Ball",
            Items::ULTRANECROZIUMZ => "Ultranecrozium Z",
            Items::UNREMARKABLETEACUP => "Unremarkable Teacup",
            Items::UPGRADE => "Up-Grade",
            Items::UTILITYUMBRELLA => "Utility Umbrella",
            Items::VENUSAURITE => "Venusaurite",
            Items::WACANBERRY => "Wacan Berry",
            Items::WATERGEM => "Water Gem",
            Items::WATERMEMORY => "Water Memory",
            Items::WATERSTONE => "Water Stone",
            Items::WATERIUMZ => "Waterium Z",
            Items::WATMELBERRY => "Watmel Berry",
            Items::WAVEINCENSE => "Wave Incense",
            Items::WEAKNESSPOLICY => "Weakness Policy",
            Items::WELLSPRINGMASK => "Wellspring Mask",
            Items::WEPEARBERRY => "Wepear Berry",
            Items::WHIPPEDDREAM => "Whipped Dream",
            Items::WHITEHERB => "White Herb",
            Items::WIDELENS => "Wide Lens",
            Items::WIKIBERRY => "Wiki Berry",
            Items::WISEGLASSES => "Wise Glasses",
            Items::YACHEBERRY => "Yache Berry",
            Items::ZAPPLATE => "Zap Plate",
            Items::ZOOMLENS => "Zoom Lens",
            Items::BERSERKGENE => "Berserk Gene",
            Items::BERRY => "Berry",
            Items::BITTERBERRY => "Bitter Berry",
            Items::BURNTBERRY => "Burnt Berry",
            Items::GOLDBERRY => "Gold Berry",
            Items::ICEBERRY => "Ice Berry",
            Items::MINTBERRY => "Mint Berry",
            Items::MIRACLEBERRY => "Miracle Berry",
            Items::MYSTERYBERRY => "Mystery Berry",
            Items::PINKBOW => "Pink Bow",
            Items::POLKADOTBOW => "Polkadot Bow",
            Items::PRZCUREBERRY => "PRZ Cure Berry",
            Items::PSNCUREBERRY => "PSN Cure Berry",
            Items::CRUCIBELLITE => "Crucibellite",
            Items::VILEVIAL => "Vile Vial",
        }
    }
}

impl FromNormalizedString for Items {
    fn from_normalized_str(s: &str) -> Option<Self> {
        match s {
            "" => Some(Items::NONE),
            "abilityshield" => Some(Items::ABILITYSHIELD),
            "abomasite" => Some(Items::ABOMASITE),
            "absolite" => Some(Items::ABSOLITE),
            "absorbbulb" => Some(Items::ABSORBBULB),
            "adamantcrystal" => Some(Items::ADAMANTCRYSTAL),
            "adamantorb" => Some(Items::ADAMANTORB),
            "adrenalineorb" => Some(Items::ADRENALINEORB),
            "aerodactylite" => Some(Items::AERODACTYLITE),
            "aggronite" => Some(Items::AGGRONITE),
            "aguavberry" => Some(Items::AGUAVBERRY),
            "airballoon" => Some(Items::AIRBALLOON),
            "alakazite" => Some(Items::ALAKAZITE),
            "aloraichiumz" => Some(Items::ALORAICHIUMZ),
            "altarianite" => Some(Items::ALTARIANITE),
            "ampharosite" => Some(Items::AMPHAROSITE),
            "apicotberry" => Some(Items::APICOTBERRY),
            "armorfossil" => Some(Items::ARMORFOSSIL),
            "aspearberry" => Some(Items::ASPEARBERRY),
            "assaultvest" => Some(Items::ASSAULTVEST),
            "audinite" => Some(Items::AUDINITE),
            "auspiciousarmor" => Some(Items::AUSPICIOUSARMOR),
            "babiriberry" => Some(Items::BABIRIBERRY),
            "banettite" => Some(Items::BANETTITE),
            "beastball" => Some(Items::BEASTBALL),
            "beedrillite" => Some(Items::BEEDRILLITE),
            "belueberry" => Some(Items::BELUEBERRY),
            "berryjuice" => Some(Items::BERRYJUICE),
            "berrysweet" => Some(Items::BERRYSWEET),
            "bignugget" => Some(Items::BIGNUGGET),
            "bigroot" => Some(Items::BIGROOT),
            "bindingband" => Some(Items::BINDINGBAND),
            "blackbelt" => Some(Items::BLACKBELT),
            "blackglasses" => Some(Items::BLACKGLASSES),
            "blacksludge" => Some(Items::BLACKSLUDGE),
            "blastoisinite" => Some(Items::BLASTOISINITE),
            "blazikenite" => Some(Items::BLAZIKENITE),
            "blueorb" => Some(Items::BLUEORB),
            "blukberry" => Some(Items::BLUKBERRY),
            "blunderpolicy" => Some(Items::BLUNDERPOLICY),
            "boosterenergy" => Some(Items::BOOSTERENERGY),
            "bottlecap" => Some(Items::BOTTLECAP),
            "brightpowder" => Some(Items::BRIGHTPOWDER),
            "buggem" => Some(Items::BUGGEM),
            "bugmemory" => Some(Items::BUGMEMORY),
            "buginiumz" => Some(Items::BUGINIUMZ),
            "burndrive" => Some(Items::BURNDRIVE),
            "cameruptite" => Some(Items::CAMERUPTITE),
            "cellbattery" => Some(Items::CELLBATTERY),
            "charcoal" => Some(Items::CHARCOAL),
            "charizarditex" => Some(Items::CHARIZARDITEX),
            "charizarditey" => Some(Items::CHARIZARDITEY),
            "chartiberry" => Some(Items::CHARTIBERRY),
            "cheriberry" => Some(Items::CHERIBERRY),
            "cherishball" => Some(Items::CHERISHBALL),
            "chestoberry" => Some(Items::CHESTOBERRY),
            "chilanberry" => Some(Items::CHILANBERRY),
            "chilldrive" => Some(Items::CHILLDRIVE),
            "chippedpot" => Some(Items::CHIPPEDPOT),
            "choiceband" => Some(Items::CHOICEBAND),
            "choicescarf" => Some(Items::CHOICESCARF),
            "choicespecs" => Some(Items::CHOICESPECS),
            "chopleberry" => Some(Items::CHOPLEBERRY),
            "clawfossil" => Some(Items::CLAWFOSSIL),
            "clearamulet" => Some(Items::CLEARAMULET),
            "cloversweet" => Some(Items::CLOVERSWEET),
            "cobaberry" => Some(Items::COBABERRY),
            "colburberry" => Some(Items::COLBURBERRY),
            "cornerstonemask" => Some(Items::CORNERSTONEMASK),
            "cornnberry" => Some(Items::CORNNBERRY),
            "coverfossil" => Some(Items::COVERFOSSIL),
            "covertcloak" => Some(Items::COVERTCLOAK),
            "crackedpot" => Some(Items::CRACKEDPOT),
            "custapberry" => Some(Items::CUSTAPBERRY),
            "damprock" => Some(Items::DAMPROCK),
            "darkgem" => Some(Items::DARKGEM),
            "darkmemory" => Some(Items::DARKMEMORY),
            "darkiniumz" => Some(Items::DARKINIUMZ),
            "dawnstone" => Some(Items::DAWNSTONE),
            "decidiumz" => Some(Items::DECIDIUMZ),
            "deepseascale" => Some(Items::DEEPSEASCALE),
            "deepseatooth" => Some(Items::DEEPSEATOOTH),
            "destinyknot" => Some(Items::DESTINYKNOT),
            "diancite" => Some(Items::DIANCITE),
            "diveball" => Some(Items::DIVEBALL),
            "domefossil" => Some(Items::DOMEFOSSIL),
            "dousedrive" => Some(Items::DOUSEDRIVE),
            "dracoplate" => Some(Items::DRACOPLATE),
            "dragonfang" => Some(Items::DRAGONFANG),
            "dragongem" => Some(Items::DRAGONGEM),
            "dragonmemory" => Some(Items::DRAGONMEMORY),
            "dragonscale" => Some(Items::DRAGONSCALE),
            "dragoniumz" => Some(Items::DRAGONIUMZ),
            "dreadplate" => Some(Items::DREADPLATE),
            "dreamball" => Some(Items::DREAMBALL),
            "dubiousdisc" => Some(Items::DUBIOUSDISC),
            "durinberry" => Some(Items::DURINBERRY),
            "duskball" => Some(Items::DUSKBALL),
            "duskstone" => Some(Items::DUSKSTONE),
            "earthplate" => Some(Items::EARTHPLATE),
            "eeviumz" => Some(Items::EEVIUMZ),
            "ejectbutton" => Some(Items::EJECTBUTTON),
            "ejectpack" => Some(Items::EJECTPACK),
            "electirizer" => Some(Items::ELECTIRIZER),
            "electricgem" => Some(Items::ELECTRICGEM),
            "electricmemory" => Some(Items::ELECTRICMEMORY),
            "electricseed" => Some(Items::ELECTRICSEED),
            "electriumz" => Some(Items::ELECTRIUMZ),
            "enigmaberry" => Some(Items::ENIGMABERRY),
            "eviolite" => Some(Items::EVIOLITE),
            "expertbelt" => Some(Items::EXPERTBELT),
            "fairiumz" => Some(Items::FAIRIUMZ),
            "fairyfeather" => Some(Items::FAIRYFEATHER),
            "fairygem" => Some(Items::FAIRYGEM),
            "fairymemory" => Some(Items::FAIRYMEMORY),
            "fastball" => Some(Items::FASTBALL),
            "fightinggem" => Some(Items::FIGHTINGGEM),
            "fightingmemory" => Some(Items::FIGHTINGMEMORY),
            "fightiniumz" => Some(Items::FIGHTINIUMZ),
            "figyberry" => Some(Items::FIGYBERRY),
            "firegem" => Some(Items::FIREGEM),
            "firememory" => Some(Items::FIREMEMORY),
            "firestone" => Some(Items::FIRESTONE),
            "firiumz" => Some(Items::FIRIUMZ),
            "fistplate" => Some(Items::FISTPLATE),
            "flameorb" => Some(Items::FLAMEORB),
            "flameplate" => Some(Items::FLAMEPLATE),
            "floatstone" => Some(Items::FLOATSTONE),
            "flowersweet" => Some(Items::FLOWERSWEET),
            "flyinggem" => Some(Items::FLYINGGEM),
            "flyingmemory" => Some(Items::FLYINGMEMORY),
            "flyiniumz" => Some(Items::FLYINIUMZ),
            "focusband" => Some(Items::FOCUSBAND),
            "focussash" => Some(Items::FOCUSSASH),
            "fossilizedbird" => Some(Items::FOSSILIZEDBIRD),
            "fossilizeddino" => Some(Items::FOSSILIZEDDINO),
            "fossilizeddrake" => Some(Items::FOSSILIZEDDRAKE),
            "fossilizedfish" => Some(Items::FOSSILIZEDFISH),
            "friendball" => Some(Items::FRIENDBALL),
            "fullincense" => Some(Items::FULLINCENSE),
            "galaricacuff" => Some(Items::GALARICACUFF),
            "galaricawreath" => Some(Items::GALARICAWREATH),
            "galladite" => Some(Items::GALLADITE),
            "ganlonberry" => Some(Items::GANLONBERRY),
            "garchompite" => Some(Items::GARCHOMPITE),
            "gardevoirite" => Some(Items::GARDEVOIRITE),
            "gengarite" => Some(Items::GENGARITE),
            "ghostgem" => Some(Items::GHOSTGEM),
            "ghostmemory" => Some(Items::GHOSTMEMORY),
            "ghostiumz" => Some(Items::GHOSTIUMZ),
            "glalitite" => Some(Items::GLALITITE),
            "goldbottlecap" => Some(Items::GOLDBOTTLECAP),
            "grassgem" => Some(Items::GRASSGEM),
            "grassmemory" => Some(Items::GRASSMEMORY),
            "grassiumz" => Some(Items::GRASSIUMZ),
            "grassyseed" => Some(Items::GRASSYSEED),
            "greatball" => Some(Items::GREATBALL),
            "grepaberry" => Some(Items::GREPABERRY),
            "gripclaw" => Some(Items::GRIPCLAW),
            "griseouscore" => Some(Items::GRISEOUSCORE),
            "griseousorb" => Some(Items::GRISEOUSORB),
            "groundgem" => Some(Items::GROUNDGEM),
            "groundmemory" => Some(Items::GROUNDMEMORY),
            "groundiumz" => Some(Items::GROUNDIUMZ),
            "gyaradosite" => Some(Items::GYARADOSITE),
            "habanberry" => Some(Items::HABANBERRY),
            "hardstone" => Some(Items::HARDSTONE),
            "healball" => Some(Items::HEALBALL),
            "hearthflamemask" => Some(Items::HEARTHFLAMEMASK),
            "heatrock" => Some(Items::HEATROCK),
            "heavyball" => Some(Items::HEAVYBALL),
            "heavydutyboots" => Some(Items::HEAVYDUTYBOOTS),
            "helixfossil" => Some(Items::HELIXFOSSIL),
            "heracronite" => Some(Items::HERACRONITE),
            "hondewberry" => Some(Items::HONDEWBERRY),
            "houndoominite" => Some(Items::HOUNDOOMINITE),
            "iapapaberry" => Some(Items::IAPAPABERRY),
            "icegem" => Some(Items::ICEGEM),
            "icememory" => Some(Items::ICEMEMORY),
            "icestone" => Some(Items::ICESTONE),
            "icicleplate" => Some(Items::ICICLEPLATE),
            "iciumz" => Some(Items::ICIUMZ),
            "icyrock" => Some(Items::ICYROCK),
            "inciniumz" => Some(Items::INCINIUMZ),
            "insectplate" => Some(Items::INSECTPLATE),
            "ironball" => Some(Items::IRONBALL),
            "ironplate" => Some(Items::IRONPLATE),
            "jabocaberry" => Some(Items::JABOCABERRY),
            "jawfossil" => Some(Items::JAWFOSSIL),
            "kasibberry" => Some(Items::KASIBBERRY),
            "kebiaberry" => Some(Items::KEBIABERRY),
            "keeberry" => Some(Items::KEEBERRY),
            "kelpsyberry" => Some(Items::KELPSYBERRY),
            "kangaskhanite" => Some(Items::KANGASKHANITE),
            "kingsrock" => Some(Items::KINGSROCK),
            "kommoniumz" => Some(Items::KOMMONIUMZ),
            "laggingtail" => Some(Items::LAGGINGTAIL),
            "lansatberry" => Some(Items::LANSATBERRY),
            "latiasite" => Some(Items::LATIASITE),
            "latiosite" => Some(Items::LATIOSITE),
            "laxincense" => Some(Items::LAXINCENSE),
            "leafstone" => Some(Items::LEAFSTONE),
            "leek" => Some(Items::LEEK),
            "leftovers" => Some(Items::LEFTOVERS),
            "leppaberry" => Some(Items::LEPPABERRY),
            "levelball" => Some(Items::LEVELBALL),
            "liechiberry" => Some(Items::LIECHIBERRY),
            "lifeorb" => Some(Items::LIFEORB),
            "lightball" => Some(Items::LIGHTBALL),
            "lightclay" => Some(Items::LIGHTCLAY),
            "loadeddice" => Some(Items::LOADEDDICE),
            "lopunnite" => Some(Items::LOPUNNITE),
            "loveball" => Some(Items::LOVEBALL),
            "lovesweet" => Some(Items::LOVESWEET),
            "lucarionite" => Some(Items::LUCARIONITE),
            "luckypunch" => Some(Items::LUCKYPUNCH),
            "lumberry" => Some(Items::LUMBERRY),
            "luminousmoss" => Some(Items::LUMINOUSMOSS),
            "lunaliumz" => Some(Items::LUNALIUMZ),
            "lureball" => Some(Items::LUREBALL),
            "lustrousglobe" => Some(Items::LUSTROUSGLOBE),
            "lustrousorb" => Some(Items::LUSTROUSORB),
            "luxuryball" => Some(Items::LUXURYBALL),
            "lycaniumz" => Some(Items::LYCANIUMZ),
            "machobrace" => Some(Items::MACHOBRACE),
            "magmarizer" => Some(Items::MAGMARIZER),
            "magnet" => Some(Items::MAGNET),
            "magoberry" => Some(Items::MAGOBERRY),
            "magostberry" => Some(Items::MAGOSTBERRY),
            "mail" => Some(Items::MAIL),
            "maliciousarmor" => Some(Items::MALICIOUSARMOR),
            "manectite" => Some(Items::MANECTITE),
            "marangaberry" => Some(Items::MARANGABERRY),
            "marshadiumz" => Some(Items::MARSHADIUMZ),
            "masterball" => Some(Items::MASTERBALL),
            "masterpieceteacup" => Some(Items::MASTERPIECETEACUP),
            "mawilite" => Some(Items::MAWILITE),
            "meadowplate" => Some(Items::MEADOWPLATE),
            "medichamite" => Some(Items::MEDICHAMITE),
            "mentalherb" => Some(Items::MENTALHERB),
            "metagrossite" => Some(Items::METAGROSSITE),
            "metalalloy" => Some(Items::METALALLOY),
            "metalcoat" => Some(Items::METALCOAT),
            "metalpowder" => Some(Items::METALPOWDER),
            "metronome" => Some(Items::METRONOME),
            "mewniumz" => Some(Items::MEWNIUMZ),
            "mewtwonitex" => Some(Items::MEWTWONITEX),
            "mewtwonitey" => Some(Items::MEWTWONITEY),
            "micleberry" => Some(Items::MICLEBERRY),
            "mimikiumz" => Some(Items::MIMIKIUMZ),
            "mindplate" => Some(Items::MINDPLATE),
            "miracleseed" => Some(Items::MIRACLESEED),
            "mirrorherb" => Some(Items::MIRRORHERB),
            "mistyseed" => Some(Items::MISTYSEED),
            "moonball" => Some(Items::MOONBALL),
            "moonstone" => Some(Items::MOONSTONE),
            "muscleband" => Some(Items::MUSCLEBAND),
            "mysticwater" => Some(Items::MYSTICWATER),
            "nanabberry" => Some(Items::NANABBERRY),
            "nestball" => Some(Items::NESTBALL),
            "netball" => Some(Items::NETBALL),
            "nevermeltice" => Some(Items::NEVERMELTICE),
            "nomelberry" => Some(Items::NOMELBERRY),
            "normalgem" => Some(Items::NORMALGEM),
            "normaliumz" => Some(Items::NORMALIUMZ),
            "occaberry" => Some(Items::OCCABERRY),
            "oddincense" => Some(Items::ODDINCENSE),
            "oldamber" => Some(Items::OLDAMBER),
            "oranberry" => Some(Items::ORANBERRY),
            "ovalstone" => Some(Items::OVALSTONE),
            "pamtreberry" => Some(Items::PAMTREBERRY),
            "parkball" => Some(Items::PARKBALL),
            "passhoberry" => Some(Items::PASSHOBERRY),
            "payapaberry" => Some(Items::PAYAPABERRY),
            "pechaberry" => Some(Items::PECHABERRY),
            "persimberry" => Some(Items::PERSIMBERRY),
            "petayaberry" => Some(Items::PETAYABERRY),
            "pidgeotite" => Some(Items::PIDGEOTITE),
            "pikaniumz" => Some(Items::PIKANIUMZ),
            "pikashuniumz" => Some(Items::PIKASHUNIUMZ),
            "pinapberry" => Some(Items::PINAPBERRY),
            "pinsirite" => Some(Items::PINSIRITE),
            "pixieplate" => Some(Items::PIXIEPLATE),
            "plumefossil" => Some(Items::PLUMEFOSSIL),
            "poisonbarb" => Some(Items::POISONBARB),
            "poisongem" => Some(Items::POISONGEM),
            "poisonmemory" => Some(Items::POISONMEMORY),
            "poisoniumz" => Some(Items::POISONIUMZ),
            "pokeball" => Some(Items::POKEBALL),
            "pomegberry" => Some(Items::POMEGBERRY),
            "poweranklet" => Some(Items::POWERANKLET),
            "powerband" => Some(Items::POWERBAND),
            "powerbelt" => Some(Items::POWERBELT),
            "powerbracer" => Some(Items::POWERBRACER),
            "powerherb" => Some(Items::POWERHERB),
            "powerlens" => Some(Items::POWERLENS),
            "powerweight" => Some(Items::POWERWEIGHT),
            "premierball" => Some(Items::PREMIERBALL),
            "primariumz" => Some(Items::PRIMARIUMZ),
            "prismscale" => Some(Items::PRISMSCALE),
            "protectivepads" => Some(Items::PROTECTIVEPADS),
            "protector" => Some(Items::PROTECTOR),
            "psychicgem" => Some(Items::PSYCHICGEM),
            "psychicmemory" => Some(Items::PSYCHICMEMORY),
            "psychicseed" => Some(Items::PSYCHICSEED),
            "psychiumz" => Some(Items::PSYCHIUMZ),
            "punchingglove" => Some(Items::PUNCHINGGLOVE),
            "qualotberry" => Some(Items::QUALOTBERRY),
            "quickball" => Some(Items::QUICKBALL),
            "quickclaw" => Some(Items::QUICKCLAW),
            "quickpowder" => Some(Items::QUICKPOWDER),
            "rabutaberry" => Some(Items::RABUTABERRY),
            "rarebone" => Some(Items::RAREBONE),
            "rawstberry" => Some(Items::RAWSTBERRY),
            "razorclaw" => Some(Items::RAZORCLAW),
            "razorfang" => Some(Items::RAZORFANG),
            "razzberry" => Some(Items::RAZZBERRY),
            "reapercloth" => Some(Items::REAPERCLOTH),
            "redcard" => Some(Items::REDCARD),
            "redorb" => Some(Items::REDORB),
            "repeatball" => Some(Items::REPEATBALL),
            "ribbonsweet" => Some(Items::RIBBONSWEET),
            "rindoberry" => Some(Items::RINDOBERRY),
            "ringtarget" => Some(Items::RINGTARGET),
            "rockgem" => Some(Items::ROCKGEM),
            "rockincense" => Some(Items::ROCKINCENSE),
            "rockmemory" => Some(Items::ROCKMEMORY),
            "rockiumz" => Some(Items::ROCKIUMZ),
            "rockyhelmet" => Some(Items::ROCKYHELMET),
            "roomservice" => Some(Items::ROOMSERVICE),
            "rootfossil" => Some(Items::ROOTFOSSIL),
            "roseincense" => Some(Items::ROSEINCENSE),
            "roseliberry" => Some(Items::ROSELIBERRY),
            "rowapberry" => Some(Items::ROWAPBERRY),
            "rustedshield" => Some(Items::RUSTEDSHIELD),
            "rustedsword" => Some(Items::RUSTEDSWORD),
            "sablenite" => Some(Items::SABLENITE),
            "sachet" => Some(Items::SACHET),
            "safariball" => Some(Items::SAFARIBALL),
            "safetygoggles" => Some(Items::SAFETYGOGGLES),
            "sailfossil" => Some(Items::SAILFOSSIL),
            "salacberry" => Some(Items::SALACBERRY),
            "salamencite" => Some(Items::SALAMENCITE),
            "sceptilite" => Some(Items::SCEPTILITE),
            "scizorite" => Some(Items::SCIZORITE),
            "scopelens" => Some(Items::SCOPELENS),
            "seaincense" => Some(Items::SEAINCENSE),
            "sharpbeak" => Some(Items::SHARPBEAK),
            "sharpedonite" => Some(Items::SHARPEDONITE),
            "shedshell" => Some(Items::SHEDSHELL),
            "shellbell" => Some(Items::SHELLBELL),
            "shinystone" => Some(Items::SHINYSTONE),
            "shockdrive" => Some(Items::SHOCKDRIVE),
            "shucaberry" => Some(Items::SHUCABERRY),
            "silkscarf" => Some(Items::SILKSCARF),
            "silverpowder" => Some(Items::SILVERPOWDER),
            "sitrusberry" => Some(Items::SITRUSBERRY),
            "skullfossil" => Some(Items::SKULLFOSSIL),
            "skyplate" => Some(Items::SKYPLATE),
            "slowbronite" => Some(Items::SLOWBRONITE),
            "smoothrock" => Some(Items::SMOOTHROCK),
            "snorliumz" => Some(Items::SNORLIUMZ),
            "snowball" => Some(Items::SNOWBALL),
            "softsand" => Some(Items::SOFTSAND),
            "solganiumz" => Some(Items::SOLGANIUMZ),
            "souldew" => Some(Items::SOULDEW),
            "spelltag" => Some(Items::SPELLTAG),
            "spelonberry" => Some(Items::SPELONBERRY),
            "splashplate" => Some(Items::SPLASHPLATE),
            "spookyplate" => Some(Items::SPOOKYPLATE),
            "sportball" => Some(Items::SPORTBALL),
            "starfberry" => Some(Items::STARFBERRY),
            "starsweet" => Some(Items::STARSWEET),
            "steelixite" => Some(Items::STEELIXITE),
            "steelgem" => Some(Items::STEELGEM),
            "steelmemory" => Some(Items::STEELMEMORY),
            "steeliumz" => Some(Items::STEELIUMZ),
            "stick" => Some(Items::STICK),
            "stickybarb" => Some(Items::STICKYBARB),
            "stoneplate" => Some(Items::STONEPLATE),
            "strangeball" => Some(Items::STRANGEBALL),
            "strawberrysweet" => Some(Items::STRAWBERRYSWEET),
            "sunstone" => Some(Items::SUNSTONE),
            "swampertite" => Some(Items::SWAMPERTITE),
            "sweetapple" => Some(Items::SWEETAPPLE),
            "syrupyapple" => Some(Items::SYRUPYAPPLE),
            "tamatoberry" => Some(Items::TAMATOBERRY),
            "tangaberry" => Some(Items::TANGABERRY),
            "tapuniumz" => Some(Items::TAPUNIUMZ),
            "tartapple" => Some(Items::TARTAPPLE),
            "terrainextender" => Some(Items::TERRAINEXTENDER),
            "thickclub" => Some(Items::THICKCLUB),
            "throatspray" => Some(Items::THROATSPRAY),
            "thunderstone" => Some(Items::THUNDERSTONE),
            "timerball" => Some(Items::TIMERBALL),
            "toxicorb" => Some(Items::TOXICORB),
            "toxicplate" => Some(Items::TOXICPLATE),
            "tr00" => Some(Items::TR_00),
            "tr01" => Some(Items::TR_01),
            "tr02" => Some(Items::TR_02),
            "tr03" => Some(Items::TR_03),
            "tr04" => Some(Items::TR_04),
            "tr05" => Some(Items::TR_05),
            "tr06" => Some(Items::TR_06),
            "tr07" => Some(Items::TR_07),
            "tr08" => Some(Items::TR_08),
            "tr09" => Some(Items::TR_09),
            "tr10" => Some(Items::TR_10),
            "tr11" => Some(Items::TR_11),
            "tr12" => Some(Items::TR_12),
            "tr13" => Some(Items::TR_13),
            "tr14" => Some(Items::TR_14),
            "tr15" => Some(Items::TR_15),
            "tr16" => Some(Items::TR_16),
            "tr17" => Some(Items::TR_17),
            "tr18" => Some(Items::TR_18),
            "tr19" => Some(Items::TR_19),
            "tr20" => Some(Items::TR_20),
            "tr21" => Some(Items::TR_21),
            "tr22" => Some(Items::TR_22),
            "tr23" => Some(Items::TR_23),
            "tr24" => Some(Items::TR_24),
            "tr25" => Some(Items::TR_25),
            "tr26" => Some(Items::TR_26),
            "tr27" => Some(Items::TR_27),
            "tr28" => Some(Items::TR_28),
            "tr29" => Some(Items::TR_29),
            "tr30" => Some(Items::TR_30),
            "tr31" => Some(Items::TR_31),
            "tr32" => Some(Items::TR_32),
            "tr33" => Some(Items::TR_33),
            "tr34" => Some(Items::TR_34),
            "tr35" => Some(Items::TR_35),
            "tr36" => Some(Items::TR_36),
            "tr37" => Some(Items::TR_37),
            "tr38" => Some(Items::TR_38),
            "tr39" => Some(Items::TR_39),
            "tr40" => Some(Items::TR_40),
            "tr41" => Some(Items::TR_41),
            "tr42" => Some(Items::TR_42),
            "tr43" => Some(Items::TR_43),
            "tr44" => Some(Items::TR_44),
            "tr45" => Some(Items::TR_45),
            "tr46" => Some(Items::TR_46),
            "tr47" => Some(Items::TR_47),
            "tr48" => Some(Items::TR_48),
            "tr49" => Some(Items::TR_49),
            "tr50" => Some(Items::TR_50),
            "tr51" => Some(Items::TR_51),
            "tr52" => Some(Items::TR_52),
            "tr53" => Some(Items::TR_53),
            "tr54" => Some(Items::TR_54),
            "tr55" => Some(Items::TR_55),
            "tr56" => Some(Items::TR_56),
            "tr57" => Some(Items::TR_57),
            "tr58" => Some(Items::TR_58),
            "tr59" => Some(Items::TR_59),
            "tr60" => Some(Items::TR_60),
            "tr61" => Some(Items::TR_61),
            "tr62" => Some(Items::TR_62),
            "tr63" => Some(Items::TR_63),
            "tr64" => Some(Items::TR_64),
            "tr65" => Some(Items::TR_65),
            "tr66" => Some(Items::TR_66),
            "tr67" => Some(Items::TR_67),
            "tr68" => Some(Items::TR_68),
            "tr69" => Some(Items::TR_69),
            "tr70" => Some(Items::TR_70),
            "tr71" => Some(Items::TR_71),
            "tr72" => Some(Items::TR_72),
            "tr73" => Some(Items::TR_73),
            "tr74" => Some(Items::TR_74),
            "tr75" => Some(Items::TR_75),
            "tr76" => Some(Items::TR_76),
            "tr77" => Some(Items::TR_77),
            "tr78" => Some(Items::TR_78),
            "tr79" => Some(Items::TR_79),
            "tr80" => Some(Items::TR_80),
            "tr81" => Some(Items::TR_81),
            "tr82" => Some(Items::TR_82),
            "tr83" => Some(Items::TR_83),
            "tr84" => Some(Items::TR_84),
            "tr85" => Some(Items::TR_85),
            "tr86" => Some(Items::TR_86),
            "tr87" => Some(Items::TR_87),
            "tr88" => Some(Items::TR_88),
            "tr89" => Some(Items::TR_89),
            "tr90" => Some(Items::TR_90),
            "tr91" => Some(Items::TR_91),
            "tr92" => Some(Items::TR_92),
            "tr93" => Some(Items::TR_93),
            "tr94" => Some(Items::TR_94),
            "tr95" => Some(Items::TR_95),
            "tr96" => Some(Items::TR_96),
            "tr97" => Some(Items::TR_97),
            "tr98" => Some(Items::TR_98),
            "tr99" => Some(Items::TR_99),
            "twistedspoon" => Some(Items::TWISTEDSPOON),
            "tyranitarite" => Some(Items::TYRANITARITE),
            "ultraball" => Some(Items::ULTRABALL),
            "ultranecroziumz" => Some(Items::ULTRANECROZIUMZ),
            "unremarkableteacup" => Some(Items::UNREMARKABLETEACUP),
            "upgrade" => Some(Items::UPGRADE),
            "utilityumbrella" => Some(Items::UTILITYUMBRELLA),
            "venusaurite" => Some(Items::VENUSAURITE),
            "wacanberry" => Some(Items::WACANBERRY),
            "watergem" => Some(Items::WATERGEM),
            "watermemory" => Some(Items::WATERMEMORY),
            "waterstone" => Some(Items::WATERSTONE),
            "wateriumz" => Some(Items::WATERIUMZ),
            "watmelberry" => Some(Items::WATMELBERRY),
            "waveincense" => Some(Items::WAVEINCENSE),
            "weaknesspolicy" => Some(Items::WEAKNESSPOLICY),
            "wellspringmask" => Some(Items::WELLSPRINGMASK),
            "wepearberry" => Some(Items::WEPEARBERRY),
            "whippeddream" => Some(Items::WHIPPEDDREAM),
            "whiteherb" => Some(Items::WHITEHERB),
            "widelens" => Some(Items::WIDELENS),
            "wikiberry" => Some(Items::WIKIBERRY),
            "wiseglasses" => Some(Items::WISEGLASSES),
            "yacheberry" => Some(Items::YACHEBERRY),
            "zapplate" => Some(Items::ZAPPLATE),
            "zoomlens" => Some(Items::ZOOMLENS),
            "berserkgene" => Some(Items::BERSERKGENE),
            "berry" => Some(Items::BERRY),
            "bitterberry" => Some(Items::BITTERBERRY),
            "burntberry" => Some(Items::BURNTBERRY),
            "goldberry" => Some(Items::GOLDBERRY),
            "iceberry" => Some(Items::ICEBERRY),
            "mintberry" => Some(Items::MINTBERRY),
            "miracleberry" => Some(Items::MIRACLEBERRY),
            "mysteryberry" => Some(Items::MYSTERYBERRY),
            "pinkbow" => Some(Items::PINKBOW),
            "polkadotbow" => Some(Items::POLKADOTBOW),
            "przcureberry" => Some(Items::PRZCUREBERRY),
            "psncureberry" => Some(Items::PSNCUREBERRY),
            "crucibellite" => Some(Items::CRUCIBELLITE),
            "vilevial" => Some(Items::VILEVIAL),
            _ => None,
        }
    }
    
    fn valid_strings() -> Vec<&'static str> {
        vec![
            "abilityshield",
            "abomasite",
            "absolite",
            "absorbbulb",
            "adamantcrystal",
            "adamantorb",
            "adrenalineorb",
            "aerodactylite",
            "aggronite",
            "aguavberry",
            "airballoon",
            "alakazite",
            "aloraichiumz",
            "altarianite",
            "ampharosite",
            "apicotberry",
            "armorfossil",
            "aspearberry",
            "assaultvest",
            "audinite",
            "auspiciousarmor",
            "babiriberry",
            "banettite",
            "beastball",
            "beedrillite",
            "belueberry",
            "berryjuice",
            "berrysweet",
            "bignugget",
            "bigroot",
            "bindingband",
            "blackbelt",
            "blackglasses",
            "blacksludge",
            "blastoisinite",
            "blazikenite",
            "blueorb",
            "blukberry",
            "blunderpolicy",
            "boosterenergy",
            "bottlecap",
            "brightpowder",
            "buggem",
            "bugmemory",
            "buginiumz",
            "burndrive",
            "cameruptite",
            "cellbattery",
            "charcoal",
            "charizarditex",
            "charizarditey",
            "chartiberry",
            "cheriberry",
            "cherishball",
            "chestoberry",
            "chilanberry",
            "chilldrive",
            "chippedpot",
            "choiceband",
            "choicescarf",
            "choicespecs",
            "chopleberry",
            "clawfossil",
            "clearamulet",
            "cloversweet",
            "cobaberry",
            "colburberry",
            "cornerstonemask",
            "cornnberry",
            "coverfossil",
            "covertcloak",
            "crackedpot",
            "custapberry",
            "damprock",
            "darkgem",
            "darkmemory",
            "darkiniumz",
            "dawnstone",
            "decidiumz",
            "deepseascale",
            "deepseatooth",
            "destinyknot",
            "diancite",
            "diveball",
            "domefossil",
            "dousedrive",
            "dracoplate",
            "dragonfang",
            "dragongem",
            "dragonmemory",
            "dragonscale",
            "dragoniumz",
            "dreadplate",
            "dreamball",
            "dubiousdisc",
            "durinberry",
            "duskball",
            "duskstone",
            "earthplate",
            "eeviumz",
            "ejectbutton",
            "ejectpack",
            "electirizer",
            "electricgem",
            "electricmemory",
            "electricseed",
            "electriumz",
            "enigmaberry",
            "eviolite",
            "expertbelt",
            "fairiumz",
            "fairyfeather",
            "fairygem",
            "fairymemory",
            "fastball",
            "fightinggem",
            "fightingmemory",
            "fightiniumz",
            "figyberry",
            "firegem",
            "firememory",
            "firestone",
            "firiumz",
            "fistplate",
            "flameorb",
            "flameplate",
            "floatstone",
            "flowersweet",
            "flyinggem",
            "flyingmemory",
            "flyiniumz",
            "focusband",
            "focussash",
            "fossilizedbird",
            "fossilizeddino",
            "fossilizeddrake",
            "fossilizedfish",
            "friendball",
            "fullincense",
            "galaricacuff",
            "galaricawreath",
            "galladite",
            "ganlonberry",
            "garchompite",
            "gardevoirite",
            "gengarite",
            "ghostgem",
            "ghostmemory",
            "ghostiumz",
            "glalitite",
            "goldbottlecap",
            "grassgem",
            "grassmemory",
            "grassiumz",
            "grassyseed",
            "greatball",
            "grepaberry",
            "gripclaw",
            "griseouscore",
            "griseousorb",
            "groundgem",
            "groundmemory",
            "groundiumz",
            "gyaradosite",
            "habanberry",
            "hardstone",
            "healball",
            "hearthflamemask",
            "heatrock",
            "heavyball",
            "heavydutyboots",
            "helixfossil",
            "heracronite",
            "hondewberry",
            "houndoominite",
            "iapapaberry",
            "icegem",
            "icememory",
            "icestone",
            "icicleplate",
            "iciumz",
            "icyrock",
            "inciniumz",
            "insectplate",
            "ironball",
            "ironplate",
            "jabocaberry",
            "jawfossil",
            "kasibberry",
            "kebiaberry",
            "keeberry",
            "kelpsyberry",
            "kangaskhanite",
            "kingsrock",
            "kommoniumz",
            "laggingtail",
            "lansatberry",
            "latiasite",
            "latiosite",
            "laxincense",
            "leafstone",
            "leek",
            "leftovers",
            "leppaberry",
            "levelball",
            "liechiberry",
            "lifeorb",
            "lightball",
            "lightclay",
            "loadeddice",
            "lopunnite",
            "loveball",
            "lovesweet",
            "lucarionite",
            "luckypunch",
            "lumberry",
            "luminousmoss",
            "lunaliumz",
            "lureball",
            "lustrousglobe",
            "lustrousorb",
            "luxuryball",
            "lycaniumz",
            "machobrace",
            "magmarizer",
            "magnet",
            "magoberry",
            "magostberry",
            "mail",
            "maliciousarmor",
            "manectite",
            "marangaberry",
            "marshadiumz",
            "masterball",
            "masterpieceteacup",
            "mawilite",
            "meadowplate",
            "medichamite",
            "mentalherb",
            "metagrossite",
            "metalalloy",
            "metalcoat",
            "metalpowder",
            "metronome",
            "mewniumz",
            "mewtwonitex",
            "mewtwonitey",
            "micleberry",
            "mimikiumz",
            "mindplate",
            "miracleseed",
            "mirrorherb",
            "mistyseed",
            "moonball",
            "moonstone",
            "muscleband",
            "mysticwater",
            "nanabberry",
            "nestball",
            "netball",
            "nevermeltice",
            "nomelberry",
            "normalgem",
            "normaliumz",
            "occaberry",
            "oddincense",
            "oldamber",
            "oranberry",
            "ovalstone",
            "pamtreberry",
            "parkball",
            "passhoberry",
            "payapaberry",
            "pechaberry",
            "persimberry",
            "petayaberry",
            "pidgeotite",
            "pikaniumz",
            "pikashuniumz",
            "pinapberry",
            "pinsirite",
            "pixieplate",
            "plumefossil",
            "poisonbarb",
            "poisongem",
            "poisonmemory",
            "poisoniumz",
            "pokeball",
            "pomegberry",
            "poweranklet",
            "powerband",
            "powerbelt",
            "powerbracer",
            "powerherb",
            "powerlens",
            "powerweight",
            "premierball",
            "primariumz",
            "prismscale",
            "protectivepads",
            "protector",
            "psychicgem",
            "psychicmemory",
            "psychicseed",
            "psychiumz",
            "punchingglove",
            "qualotberry",
            "quickball",
            "quickclaw",
            "quickpowder",
            "rabutaberry",
            "rarebone",
            "rawstberry",
            "razorclaw",
            "razorfang",
            "razzberry",
            "reapercloth",
            "redcard",
            "redorb",
            "repeatball",
            "ribbonsweet",
            "rindoberry",
            "ringtarget",
            "rockgem",
            "rockincense",
            "rockmemory",
            "rockiumz",
            "rockyhelmet",
            "roomservice",
            "rootfossil",
            "roseincense",
            "roseliberry",
            "rowapberry",
            "rustedshield",
            "rustedsword",
            "sablenite",
            "sachet",
            "safariball",
            "safetygoggles",
            "sailfossil",
            "salacberry",
            "salamencite",
            "sceptilite",
            "scizorite",
            "scopelens",
            "seaincense",
            "sharpbeak",
            "sharpedonite",
            "shedshell",
            "shellbell",
            "shinystone",
            "shockdrive",
            "shucaberry",
            "silkscarf",
            "silverpowder",
            "sitrusberry",
            "skullfossil",
            "skyplate",
            "slowbronite",
            "smoothrock",
            "snorliumz",
            "snowball",
            "softsand",
            "solganiumz",
            "souldew",
            "spelltag",
            "spelonberry",
            "splashplate",
            "spookyplate",
            "sportball",
            "starfberry",
            "starsweet",
            "steelixite",
            "steelgem",
            "steelmemory",
            "steeliumz",
            "stick",
            "stickybarb",
            "stoneplate",
            "strangeball",
            "strawberrysweet",
            "sunstone",
            "swampertite",
            "sweetapple",
            "syrupyapple",
            "tamatoberry",
            "tangaberry",
            "tapuniumz",
            "tartapple",
            "terrainextender",
            "thickclub",
            "throatspray",
            "thunderstone",
            "timerball",
            "toxicorb",
            "toxicplate",
            "tr00",
            "tr01",
            "tr02",
            "tr03",
            "tr04",
            "tr05",
            "tr06",
            "tr07",
            "tr08",
            "tr09",
            "tr10",
            "tr11",
            "tr12",
            "tr13",
            "tr14",
            "tr15",
            "tr16",
            "tr17",
            "tr18",
            "tr19",
            "tr20",
            "tr21",
            "tr22",
            "tr23",
            "tr24",
            "tr25",
            "tr26",
            "tr27",
            "tr28",
            "tr29",
            "tr30",
            "tr31",
            "tr32",
            "tr33",
            "tr34",
            "tr35",
            "tr36",
            "tr37",
            "tr38",
            "tr39",
            "tr40",
            "tr41",
            "tr42",
            "tr43",
            "tr44",
            "tr45",
            "tr46",
            "tr47",
            "tr48",
            "tr49",
            "tr50",
            "tr51",
            "tr52",
            "tr53",
            "tr54",
            "tr55",
            "tr56",
            "tr57",
            "tr58",
            "tr59",
            "tr60",
            "tr61",
            "tr62",
            "tr63",
            "tr64",
            "tr65",
            "tr66",
            "tr67",
            "tr68",
            "tr69",
            "tr70",
            "tr71",
            "tr72",
            "tr73",
            "tr74",
            "tr75",
            "tr76",
            "tr77",
            "tr78",
            "tr79",
            "tr80",
            "tr81",
            "tr82",
            "tr83",
            "tr84",
            "tr85",
            "tr86",
            "tr87",
            "tr88",
            "tr89",
            "tr90",
            "tr91",
            "tr92",
            "tr93",
            "tr94",
            "tr95",
            "tr96",
            "tr97",
            "tr98",
            "tr99",
            "twistedspoon",
            "tyranitarite",
            "ultraball",
            "ultranecroziumz",
            "unremarkableteacup",
            "upgrade",
            "utilityumbrella",
            "venusaurite",
            "wacanberry",
            "watergem",
            "watermemory",
            "waterstone",
            "wateriumz",
            "watmelberry",
            "waveincense",
            "weaknesspolicy",
            "wellspringmask",
            "wepearberry",
            "whippeddream",
            "whiteherb",
            "widelens",
            "wikiberry",
            "wiseglasses",
            "yacheberry",
            "zapplate",
            "zoomlens",
            "berserkgene",
            "berry",
            "bitterberry",
            "burntberry",
            "goldberry",
            "iceberry",
            "mintberry",
            "miracleberry",
            "mysteryberry",
            "pinkbow",
            "polkadotbow",
            "przcureberry",
            "psncureberry",
            "crucibellite",
            "vilevial",
        ]
    }
}

impl fmt::Display for Items {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.display_name())
    }
}

impl Default for Items {
    fn default() -> Self {
        Items::NONE
    }
}
